import type { TopicContent } from "./types";

export const artificialIntelligence: TopicContent = {
  slug: "artificial-intelligence",
  hero:
    "Artificial Intelligence is reshaping society — from spam filters to self-driving cars to autonomous weapons. This module unpacks what AI really is, how machine learning works, the limits of narrow AI, the dangers of algorithmic bias and the deep question of who is responsible when AI gets it wrong.",
  tags: ["AI", "MACHINE LEARNING", "NARROW AI", "ROBOTS", "BIAS", "RESPONSIBILITY"],
  sections: [
    {
      id: "ai-ml",
      code: "01",
      title: "AI & Machine Learning",
      explanation:
        "Artificial Intelligence (AI) is the simulation of human intelligence by computer systems. Machine learning (ML) is the branch of AI where systems learn from data rather than being explicitly programmed.",
      bullets: [
        "AI = simulation of human intelligence by computer systems (perception, reasoning, learning).",
        "Machine learning = systems learn from data rather than being programmed for every rule.",
        "ML systems analyse real-time and historical data.",
        "ML systems detect patterns in data.",
        "ML systems improve automatically as they receive more data.",
        "ML does not require explicit programming for every rule or situation.",
        "Robots are programmable machines that carry out physical actions, often using AI.",
      ],
      paragraphs: [
        "Traditional programming follows fixed rules a developer writes. ML flips this around: you give the system many examples (training data) and it builds its own rules to make predictions or decisions on new data it has never seen.",
        "Because ML improves with more data, the systems get more accurate over time — but they also inherit the strengths and weaknesses of whatever data they were trained on.",
        "Robots combine AI software with physical hardware: sensors, actuators and motors. Industrial robots build cars, surgical robots assist operations, and domestic robots vacuum floors.",
      ],
      quiz: [
        { q: "Artificial Intelligence is best defined as…", options: ["The simulation of human intelligence (perception, reasoning, learning) by computer systems", "A type of internet cable", "A new programming language", "A faster CPU"], answer: 0, why: "Spec definition of AI." },
        { q: "Machine learning systems improve mainly by…", options: ["Receiving more data and adjusting internal patterns", "Being unplugged regularly", "Stopping all training", "Being uninstalled"], answer: 0, why: "Data-driven self-improvement." },
        { q: "Machine learning differs from traditional programming because it does NOT require…", options: ["Explicit, hand-written rules for every situation", "Any input data", "A computer to run on", "Pattern recognition"], answer: 0, why: "ML learns patterns from data, not hard-coded rules." },
        { q: "Which best describes a robot?", options: ["A programmable machine combining AI software with sensors and actuators for physical actions", "A pure pen-and-paper algorithm", "A static database", "A static webpage"], answer: 0, why: "Robots = software + physical hardware." },
        { q: "Training data is used to…", options: ["Teach an ML model the patterns it should recognise", "Cool the CPU", "Power the screen", "Print labels"], answer: 0, why: "Examples shape the model's predictions." },
        { q: "Traditional rule-based programming relies on…", options: ["Fixed rules written by a developer", "Self-learned patterns", "No rules at all", "Random outputs only"], answer: 0, why: "Developer specifies every rule." },
        { q: "Machine learning systems can analyse…", options: ["Both real-time and historical data", "Only paper records", "Only audio", "Only voice commands"], answer: 0, why: "ML works across many data sources." },
        { q: "True/False: machine learning systems detect patterns in data without being given the rules for those patterns.", options: ["True", "False"], answer: 0, why: "Core ML behaviour." },
        { q: "Which is an example of a robot that uses AI?", options: ["A self-driving car using perception and control models", "A hammer", "A pen", "A static spoon"], answer: 0, why: "Sensor-rich, AI-driven physical machine." },
        { q: "In general, ML accuracy will…", options: ["Improve with more high-quality, relevant data", "Always decrease as more data arrives", "Never change after training", "Drop to zero with use"], answer: 0, why: "More good data = better patterns (garbage in, garbage out otherwise)." },
      ],
    },
    {
      id: "narrow-ai",
      code: "02",
      title: "Narrow AI",
      explanation:
        "Narrow (or 'weak') AI is built to perform one specific task very well. It cannot generalise. Almost every real-world AI in 2026 is narrow AI.",
      bullets: [
        "Narrow AI performs ONE specific task.",
        "Examples: spam filters that classify email.",
        "Examples: social media monitoring (content moderation).",
        "Examples: facial recognition (unlock phones, surveillance).",
        "Examples: fingerprint recognition (security access).",
        "Examples: recommendation systems (Netflix, YouTube, Spotify).",
        "Examples: voice assistants (Siri, Alexa, Google Assistant).",
        "Examples: self-driving cars (perception + control).",
        "Examples: lethal autonomous weapons (military drones).",
        "Narrow AI fails outside its designed problem space.",
      ],
      paragraphs: [
        "A spam filter is brilliant at sorting email but cannot drive a car; a self-driving model cannot recommend movies. Each system is tightly specialised — feed it the wrong problem and the results are nonsense.",
        "Lethal autonomous weapons are one of the most controversial uses of narrow AI: machines deciding which target to engage without human approval raises severe ethical and legal concerns.",
      ],
      quiz: [
        { q: "Narrow AI is AI that is…", options: ["Specialised in performing ONE specific task very well", "Good at every possible task", "Truly conscious and self-aware", "Completely random in behaviour"], answer: 0, why: "Spec definition — single-task focus, cannot generalise." },
        { q: "Which is NOT an example of narrow AI?", options: ["Spam filters", "Facial recognition", "Voice assistants", "A fully conscious general-purpose thinker"], answer: 3, why: "That would be AGI; narrow AI cannot generalise." },
        { q: "Self-driving cars are an example of…", options: ["Narrow AI for perception and vehicle control", "General AI with consciousness", "No AI at all", "Pure rule-based systems"], answer: 0, why: "Specialised perception + control task." },
        { q: "Recommendation systems on Netflix or Spotify work by…", options: ["Suggesting content based on patterns in user behaviour", "Picking random items always", "Asking the user every minute", "Following government rules"], answer: 0, why: "Pattern-based personalisation." },
        { q: "Voice assistants such as Siri or Alexa perform…", options: ["Speech recognition and language responses (narrow task)", "Plumbing", "Tree planting", "Train driving"], answer: 0, why: "Narrow speech-processing AI." },
        { q: "Why are lethal autonomous weapons especially controversial?", options: ["Machines may select and engage targets without human approval, raising ethical/legal concerns", "They run on batteries", "They are too cheap", "They sing too loud"], answer: 0, why: "Removes human judgement from life-or-death decisions." },
        { q: "Narrow AI typically FAILS when…", options: ["Asked to operate outside its designed task / problem space", "Operating inside its task", "Given new training data", "Switched on"], answer: 0, why: "Does not generalise across tasks." },
        { q: "A spam filter classifying email is a narrow AI specialised in…", options: ["Text classification", "Driving cars", "Cooking food", "Mining metal"], answer: 0, why: "Single classification task." },
        { q: "Fingerprint recognition is used mainly for…", options: ["Biometric security access (unlocking phones, building entry)", "Voice typing", "Driving cars", "Cooking"], answer: 0, why: "Biometric authentication." },
        { q: "Automated social media content moderation uses narrow AI to…", options: ["Detect and flag harmful or rule-breaking content at scale", "Build search engines", "Cook food", "Mine ore"], answer: 0, why: "Pattern detection for moderation." },
      ],
    },
    {
      id: "bias",
      code: "03",
      title: "Algorithmic Bias",
      explanation:
        "Algorithmic bias happens when an AI system produces unfair or discriminatory outcomes — often without anyone intending it. The bias comes from the data, the algorithm or the developers.",
      bullets: [
        "Cause 1: biased training data — historical data reflects past prejudices.",
        "Cause 2: flawed algorithms — design choices amplify certain patterns.",
        "Cause 3: developer prejudice — conscious or unconscious bias in the team.",
        "AI systems may discriminate unfairly (jobs, loans, policing, healthcare).",
        "Bias is often invisible until outcomes are studied at scale.",
      ],
      paragraphs: [
        "If a hiring AI is trained on 20 years of company hiring data and that company hired mostly men, the AI will learn that 'good candidates look like the men who were hired before' and downrank women. The data itself encodes the bias.",
        "Even with neutral data, design choices — what counts as success, what features are used — can amplify bias. And the developers themselves bring assumptions into how the system is built and tested.",
        "Real-world consequences are severe: biased facial recognition has misidentified innocent people; biased risk-scoring has unfairly denied loans or parole.",
      ],
      quiz: [
        { q: "Algorithmic bias is best defined as…", options: ["AI systems producing unfair or discriminatory outcomes for certain groups", "Algorithms running too fast", "Random output values", "Improvements in fairness"], answer: 0, why: "Unfair systematic outcomes — often unintended." },
        { q: "A hiring AI is trained on 20 years of company hiring data, most of whom were men. The likely bias is…", options: ["The AI learns to favour male candidates and downrank women", "The AI becomes perfectly neutral", "The AI hires only animals", "No bias possible"], answer: 0, why: "Biased training data → biased predictions." },
        { q: "Which is a cause of algorithmic bias?", options: ["Biased training data", "Flawed algorithm design choices", "Conscious or unconscious developer prejudice", "All of the above"], answer: 3, why: "All three are key sources named in the spec." },
        { q: "'Flawed algorithms' can cause bias because…", options: ["Design choices (features, success metrics) can amplify certain patterns unfairly", "All algorithms are perfect", "They run too slowly", "They have nice colours"], answer: 0, why: "Design decisions shape outcomes." },
        { q: "Developer prejudice influences AI through…", options: ["Choices about what to measure, what to test and what to ignore", "Better Wi-Fi", "Bigger RAM", "Larger screens"], answer: 0, why: "Human assumptions enter the system." },
        { q: "Biased AI has caused real-world harm in areas including…", options: ["Hiring, lending, policing and healthcare", "Only sports", "Only cooking", "Only weather forecasting"], answer: 0, why: "Documented discrimination cases." },
        { q: "Algorithmic bias is often INVISIBLE until…", options: ["Outcomes are studied across many users / over time", "The first day of testing", "Power is switched off", "Never"], answer: 0, why: "Pattern emerges only at scale." },
        { q: "Biased facial recognition systems have been shown to…", options: ["Misidentify innocent people, especially from underrepresented groups", "Always work perfectly", "Cure all bias", "Remove all errors"], answer: 0, why: "Documented wrongful-arrest cases." },
        { q: "True/False: algorithmic bias can come from data, the algorithm AND the developers.", options: ["True", "False"], answer: 0, why: "Three main sources combined." },
        { q: "The most effective way to reduce algorithmic bias combines…", options: ["Better quality data + careful design + diverse teams + regular audits", "Just more data", "Just faster hardware", "Just bigger models"], answer: 0, why: "Multi-pronged response required." },
      ],
    },
    {
      id: "responsibility",
      code: "04",
      title: "Responsibility & Accountability",
      explanation:
        "When an AI system causes harm, who is responsible? The creator, the data supplier, the user, or 'the algorithm'? This is one of the biggest open problems in AI law and ethics.",
      bullets: [
        "Creator responsibility — those who designed and built the system.",
        "Training data supplier responsibility — bad or biased data → harmful behaviour.",
        "User responsibility — how the system is deployed and supervised.",
        "'Black-box' systems hide their reasoning, making responsibility harder to trace.",
        "Lack of explainability makes legal accountability difficult.",
      ],
      paragraphs: [
        "A 'black-box' AI gives outputs without showing why. Deep neural networks are powerful but notoriously hard to explain. If a black-box loan model rejects you, it can be impossible to challenge the decision, because nobody (including the bank) fully understands the reasoning.",
        "Accountability typically splits across all three parties. The creator should design safely; the data supplier should provide unbiased, representative data; the user must deploy responsibly with oversight. Regulators are pushing for 'explainable AI' to make this chain of responsibility workable in law.",
      ],
      quiz: [
        { q: "When an AI system causes harm, responsibility is typically shared between…", options: ["The creator, the training data supplier and the user", "Only the keyboard", "Only the screen", "Nobody at all"], answer: 0, why: "Three-way accountability chain." },
        { q: "A 'black-box' AI is one where…", options: ["The internal reasoning behind a decision cannot be easily explained", "It will not boot up", "It cannot be turned off", "It runs only at night"], answer: 0, why: "Opaque decision-making." },
        { q: "The training data supplier is responsible for…", options: ["The quality, accuracy and fairness of the training data provided", "The Wi-Fi speed", "The hardware cost", "Marketing campaigns"], answer: 0, why: "Garbage in, garbage out." },
        { q: "End users of an AI system are responsible for…", options: ["How they deploy the system and the human oversight they apply", "Writing the operating system kernel", "Mining metals", "Cooling servers"], answer: 0, why: "Real-world use matters." },
        { q: "Explainable AI is designed to…", options: ["Make the reasoning of AI systems understandable to humans", "Be intentionally slower", "Be more black-box", "Refuse all outputs"], answer: 0, why: "Transparency enables accountability." },
        { q: "Why is accountability hardest with a black-box AI?", options: ["No one can clearly trace WHY a decision was made", "The system uses no electricity", "It is illegal to use", "It is too simple"], answer: 0, why: "Opaque reasoning blocks legal challenge." },
        { q: "Lack of explainability creates problems for…", options: ["Legal challenge, regulation and victim redress", "Better Wi-Fi", "Faster RAM", "Bigger screens"], answer: 0, why: "Courts and regulators need reasoning." },
        { q: "The creator of an AI system has a duty to…", options: ["Design and test the system safely and fairly", "Provide free updates forever", "Give free hardware", "Supply training data for free"], answer: 0, why: "Design responsibility." },
        { q: "True/False: 'the algorithm did it' is a strong legal defence in court.", options: ["True", "False"], answer: 1, why: "Liability is assigned to humans and organisations, not abstract code." },
        { q: "The most responsible approach to AI accountability combines…", options: ["Shared responsibility + explainable AI + independent audits + human oversight", "Blaming the user only", "Blaming nobody", "Using only black-box models"], answer: 0, why: "Layered safeguards." },
      ],
    },
  ],
  flashcards: [
    { category: "AI", front: "AI definition", back: "Simulation of human intelligence by computer systems — perception, reasoning, learning." },
    { category: "ML", front: "Machine learning", back: "Systems that learn from data and improve automatically rather than being explicitly programmed for every rule." },
    { category: "NARROW AI", front: "Narrow AI", back: "AI specialised in one task — fails outside its designed problem space." },
    { category: "NARROW AI", front: "Narrow AI examples", back: "Spam filters, social media monitoring, facial/fingerprint recognition, recommendations, voice assistants, self-driving cars, lethal autonomous weapons." },
    { category: "BIAS", front: "Causes of algorithmic bias", back: "Biased training data, flawed algorithms, developer prejudice." },
    { category: "BIAS", front: "Impact of bias", back: "Unfair discrimination in jobs, loans, policing, healthcare and more." },
    { category: "RESPONSIBILITY", front: "Who is responsible for AI harm?", back: "Creator, training data supplier, user — shared accountability." },
    { category: "RESPONSIBILITY", front: "Black-box AI", back: "AI whose internal reasoning is hidden/opaque — makes accountability and legal challenge much harder." },
  ],
};
