import type { TopicContent } from "./types";

export const environmentalIssues: TopicContent = {
  slug: "environmental-issues",
  hero:
    "Every digital device carries a hidden environmental cost — from the mines where its metals are extracted, through factories and data centres, to the landfill where it eventually rots. This module decodes the full footprint of computing and the laws, behaviours and technologies that can reduce it.",
  tags: ["MANUFACTURE", "ENERGY", "DISPOSAL", "WEEE", "RECYCLING", "REPLACEMENT", "REDUCE", "POSITIVE"],
  sections: [
    {
      id: "manufacture",
      code: "01",
      title: "Manufacture",
      explanation:
        "Producing a digital device requires huge amounts of raw materials, energy and water — long before the device is ever switched on. The environmental cost of a phone or laptop begins inside a mine.",
      bullets: [
        "Digital devices need raw materials such as copper, palladium and arsenic.",
        "Copper and palladium are non-renewable — Earth has a finite supply that cannot be replaced fast enough once used.",
        "Arsenic is highly toxic and dangerous to handle.",
        "Mining scars landscapes, creates waste, destroys wildlife habitats and damages ecosystems.",
        "Manufacturing consumes huge amounts of energy, most of it from fossil fuels (non-renewable).",
        "Burning fossil fuels releases CO₂, accelerating global warming and climate change.",
        "Factories produce polluted waste water containing toxic chemicals that can enter rivers and lakes.",
        "Technology production has environmental costs BEFORE devices are even turned on.",
      ],
      paragraphs: [
        "Mining for the metals inside a phone strips topsoil, diverts rivers and leaves behind huge open pits. Local wildlife loses its habitat and surrounding communities often lose access to clean water. Copper and palladium are essential for circuitry, but their supply is finite — once extracted, the planet cannot regenerate them on any useful timescale.",
        "Silicon chips are produced in cleanrooms that need vast amounts of ultra-pure water and electricity. A single chip factory can use as much power as a small city, and most of that electricity still comes from non-renewable fossil fuels, contributing directly to climate change.",
        "Waste water from chip plants and metal refineries can contain heavy metals, arsenic and solvents. If it is not treated properly it leaks into rivers and lakes, killing fish and contaminating drinking water for years afterwards.",
      ],
      quiz: [
        { q: "Which raw material used in digital devices is highly toxic and dangerous to handle during manufacture?", options: ["Copper", "Aluminium", "Arsenic", "Silicon"], answer: 2, why: "Arsenic is a toxic substance used in semiconductor manufacturing — a key spec example." },
        { q: "Why are copper and palladium classed as non-renewable resources?", options: ["They rust away within decades", "Earth has a finite supply that cannot be replenished on a useful timescale", "They are banned by international law", "They evaporate when exposed to air"], answer: 1, why: "Non-renewable means once extracted, nature cannot replace them quickly." },
        { q: "A new microchip factory opens next to a river. Which consequence is MOST likely?", options: ["Improved fish stocks", "Toxic chemicals from waste water polluting the river", "Cleaner drinking water locally", "Reduced fossil-fuel demand"], answer: 1, why: "Untreated effluent carries heavy metals and solvents into waterways." },
        { q: "Most electricity used by electronics manufacturing globally comes from…", options: ["Solar power", "Tidal power", "Fossil fuels", "Wind power"], answer: 2, why: "Global manufacturing grids remain fossil-fuel dominated, accelerating climate change." },
        { q: "Burning fossil fuels during manufacture contributes directly to…", options: ["Climate change through CO₂ emissions", "Cheaper devices for consumers", "Greater biodiversity", "Improved air quality"], answer: 0, why: "CO₂ is a greenhouse gas → global warming." },
        { q: "Which statement about mining for device materials is correct?", options: ["It regenerates habitats", "It strips topsoil and destroys wildlife habitats", "It removes CO₂ from the atmosphere", "It cools surrounding land"], answer: 1, why: "Open-pit mining causes long-term ecosystem damage." },
        { q: "A smartphone has environmental costs…", options: ["Only while in use", "Only after being recycled", "Long before it is switched on", "Only during charging"], answer: 2, why: "Mining + manufacture + transport occur pre-use." },
        { q: "Which is NOT a typical manufacturing impact?", options: ["Wildlife habitat destruction", "Polluted waste water", "Reduced global e-waste", "High fossil-fuel energy use"], answer: 2, why: "Manufacture creates future e-waste, it does not reduce it." },
        { q: "True/False: polluted factory waste water can contaminate drinking water for many years.", options: ["True", "False"], answer: 0, why: "Heavy metals persist in groundwater for decades." },
        { q: "Why is the manufacturing footprint of a phone often hidden from consumers?", options: ["It is printed on every box", "It happens overseas, far from the buyer", "It is shown in app stores", "It appears on the lock screen"], answer: 1, why: "Mines and factories are usually in distant countries, invisible to end users." },
      ],
    },
    {
      id: "energy",
      code: "02",
      title: "Energy Consumption",
      explanation:
        "Digital technology consumes electricity at every stage of its life: producing devices, operating them, storing data in data centres, and recycling them. Most of that energy is used away from the user.",
      bullets: [
        "Energy is consumed during production, operation, online data storage and recycling.",
        "Manufacture + disposal ≈ 70% of lifetime energy (mining, manufacturing, packaging, transport, recycling).",
        "Use ≈ 30% of lifetime energy (powering devices, telecoms networks, storing data).",
        "Data centres run 24/7 storing and serving huge amounts of data.",
        "Telecoms networks (masts, routers, undersea cables) consume continuous power.",
        "Cooling servers can use almost as much energy as the servers themselves.",
        "Most energy is consumed BEFORE and AFTER use, not during use itself.",
        "Technology can REDUCE energy use elsewhere: smart lighting, route planners, light sensors, intelligent systems.",
      ],
      paragraphs: [
        "When you stream a video, energy is consumed by your phone, the data centre serving the video, the network carrying it, and the cooling system stopping the servers overheating. The visible part is tiny compared to the hidden infrastructure.",
        "Because manufacture + transport + recycling dominate the lifetime footprint, keeping a device longer is often greener than upgrading to a 'more efficient' new one — the new device's production cost outweighs years of efficiency savings.",
        "Technology can also CUT energy elsewhere. Smart lighting only powers occupied rooms, route planners reduce wasted fuel, intelligent grids balance renewable supply with demand, and light sensors prevent unnecessary illumination.",
      ],
      quiz: [
        { q: "Approximately what percentage of a device's lifetime energy is consumed by manufacture and disposal combined?", options: ["10%", "30%", "70%", "95%"], answer: 2, why: "Around 70% — the hidden footprint dominates the visible 'use' phase." },
        { q: "The remaining ~30% of lifetime energy is used during…", options: ["Mining only", "Use — powering the device, telecoms networks and data centres", "Recycling only", "Advertising"], answer: 1, why: "30% covers the active 'use' phase including network + cloud." },
        { q: "Why do data centres consume vast amounts of electricity?", options: ["They are switched off at night", "They run 24/7 storing and serving data and need constant cooling", "They use only solar power", "They have small servers"], answer: 1, why: "Always-on services + cooling demands huge continuous power." },
        { q: "Cooling systems in data centres can use…", options: ["Almost as much energy as the servers themselves", "No energy at all", "Less than 1% of total energy", "Only seasonal energy"], answer: 0, why: "Heat removal is a major operating cost." },
        { q: "How can smart lighting REDUCE energy consumption?", options: ["By staying on permanently", "By only powering lights when occupants are detected", "By using bigger bulbs", "By increasing brightness"], answer: 1, why: "Sensor-driven lighting eliminates wasted illumination." },
        { q: "A driver uses a satnav route planner. The main environmental benefit is…", options: ["Reduced wasted fuel via shorter / smoother routes", "Increased emissions", "More traffic", "Higher battery wear"], answer: 0, why: "Less fuel burned = lower CO₂." },
        { q: "Telecoms networks (masts, routers, cables) consume…", options: ["Energy continuously, 24/7", "Energy only when phones ring", "No energy at all", "Energy only on weekdays"], answer: 0, why: "Network infrastructure is always-on." },
        { q: "Why might keeping an older phone be GREENER than buying a more efficient new one?", options: ["Manufacture + disposal dominate lifetime footprint", "Old phones use no power", "New phones never need charging", "Old phones are radioactive"], answer: 0, why: "Production cost outweighs years of efficiency savings." },
        { q: "Which technology helps balance renewable supply with electricity demand?", options: ["Intelligent / smart grids", "Static fuse boxes", "Analog meters", "Manual switches"], answer: 0, why: "Smart grids match supply (variable renewables) with demand." },
        { q: "Streaming a high-definition video consumes energy at…", options: ["Only the phone", "Phone + network + data centre + cooling systems", "Only the data centre", "Only the router"], answer: 1, why: "The whole delivery chain draws power for each stream." },
      ],
    },
    {
      id: "disposal",
      code: "03",
      title: "Disposal & E-waste",
      explanation:
        "Discarded digital devices become e-waste. The world produces around 50 million tonnes of it every year and only about 20% is properly recycled. The rest causes serious environmental and human harm.",
      bullets: [
        "Approximately 50 million tonnes of e-waste produced globally per year.",
        "Only around 20% is recycled responsibly.",
        "Illegal dumping in landfill causes toxic chemicals to leak: lead, mercury and cobalt contamination.",
        "Chemicals enter soil, groundwater and rivers.",
        "People living near e-waste dumps suffer poisoning, disease and long-term health problems.",
        "Many people in poorer countries salvage valuable materials from dangerous waste sites.",
        "Millions of tonnes of e-waste are dumped in developing countries every year.",
      ],
      paragraphs: [
        "Many electronics are dumped illegally in landfill sites in poorer countries. Local workers — sometimes children — burn cables to recover copper, exposing themselves to highly toxic fumes containing lead, mercury and dioxins.",
        "Heavy metals such as lead, mercury and cobalt leak slowly into the soil. Once in groundwater they are extremely difficult to remove and can poison drinking water for entire communities for decades.",
        "Long-term exposure causes serious illness, including neurological damage, organ failure and cancers. Illegal e-waste dumping causes major environmental and human harm — the human cost of careless disposal is enormous compared to the small effort of recycling responsibly.",
      ],
      quiz: [
        { q: "Approximately how much e-waste is generated globally each year?", options: ["5 million tonnes", "20 million tonnes", "50 million tonnes", "500 million tonnes"], answer: 2, why: "Around 50 Mt/year — the equivalent of ~5,000 Eiffel Towers." },
        { q: "What percentage of global e-waste is properly recycled?", options: ["Around 20%", "Around 50%", "Around 75%", "Around 95%"], answer: 0, why: "Only ~20% goes through formal recycling — the rest leaks into landfill." },
        { q: "Which toxic chemicals commonly leak from illegally dumped e-waste?", options: ["Sugar and salt", "Lead, mercury and cobalt", "Oxygen and nitrogen", "Iron and zinc only"], answer: 1, why: "Heavy metals named in the spec — all hazardous to health." },
        { q: "Why is illegal e-waste dumping in developing countries especially harmful?", options: ["Local communities — including children — burn cables and salvage parts, exposing themselves to toxins", "It boosts the local economy with no risk", "It cleans the soil", "It improves air quality"], answer: 0, why: "Vulnerable workers face poisoning and disease." },
        { q: "Leaked heavy metals from e-waste typically end up in…", options: ["The cloud", "Soil, groundwater and rivers", "Outer space", "Bookshops"], answer: 1, why: "They leach into the ground and contaminate water supplies for decades." },
        { q: "Long-term exposure to e-waste toxins can cause…", options: ["Faster Wi-Fi", "Neurological damage, organ failure and cancers", "Cleaner drinking water", "Better eyesight"], answer: 1, why: "Lead, mercury and dioxins are well-documented health hazards." },
        { q: "Why do people in poorer countries salvage from dangerous e-waste sites?", options: ["For fun", "To recover valuable metals such as copper for income", "Because the government orders it", "Because schools require it"], answer: 1, why: "Poverty pushes people into hazardous metal recovery." },
        { q: "True/False: discarded electronics decompose safely like food waste.", options: ["True", "False"], answer: 1, why: "E-waste is non-biodegradable and contains persistent toxins." },
        { q: "Which is NOT a consequence of illegal e-waste dumping?", options: ["Soil pollution", "Water contamination", "Improved biodiversity", "Long-term human illness"], answer: 2, why: "Biodiversity is reduced, not improved." },
        { q: "E-waste is best defined as…", options: ["Spam emails", "Any discarded electrical or electronic equipment", "Old paper documents", "Unused USB cables only"], answer: 1, why: "Spec definition — covers all electrical/electronic equipment." },
      ],
    },
    {
      id: "weee",
      code: "04",
      title: "WEEE Regulations",
      explanation:
        "The WEEE regulations (Waste Electrical and Electronic Equipment) are designed to reduce environmental harm from discarded electronics by forcing producers and retailers to collect, recycle and recover them properly.",
      bullets: [
        "WEEE = Waste Electrical and Electronic Equipment regulations.",
        "Set legal recycling targets.",
        "Set legal collection targets.",
        "Encourage recovery of valuable electronic components.",
        "Purpose: reduce environmental harm caused by e-waste.",
        "Retailers must offer take-back schemes for old equipment.",
      ],
      paragraphs: [
        "Before WEEE, manufacturers had no real responsibility for what happened to a product after it was sold. The regulations force them to fund proper collection and recycling, placing the cost where it belongs.",
        "Targets are set for the proportion of electronics that must be collected and recycled each year. Failing to meet them carries large fines, so producers actively support recycling networks and consumer take-back schemes.",
      ],
      quiz: [
        { q: "WEEE stands for…", options: ["World Electrical Energy Exchange", "Waste Electrical and Electronic Equipment", "Wireless Edge Electronics Effort", "Web Electronic Engineering Ethics"], answer: 1, why: "Standard regulatory name in UK and EU law." },
        { q: "The MAIN purpose of WEEE regulations is to…", options: ["Speed up phone manufacturing", "Reduce the environmental harm caused by discarded electronics", "Make electronics cheaper", "Promote new mining operations"], answer: 1, why: "Stated objective in the legislation." },
        { q: "WEEE places legal responsibility for end-of-life products on…", options: ["Consumers only", "Producers and retailers", "Schools", "Postal services"], answer: 1, why: "Extended producer responsibility — those who profit must collect/recycle." },
        { q: "Under WEEE, retailers selling new electronics must…", options: ["Refuse all returns", "Offer a take-back scheme for old equipment", "Burn old devices on site", "Send all returns to landfill"], answer: 1, why: "Take-back schemes are a legal duty." },
        { q: "What happens if a producer misses their WEEE recycling target?", options: ["Nothing — the targets are voluntary", "They can be fined", "They get a tax cut", "Customers go to prison"], answer: 1, why: "Financial penalties drive compliance." },
        { q: "WEEE sets targets for…", options: ["Mining quotas", "Collection and recycling of e-waste", "Marketing spending", "Game design"], answer: 1, why: "Both collection AND recycling rates are regulated." },
        { q: "Which scenario follows WEEE correctly?", options: ["Dumping an old laptop in a river", "Returning an old laptop to the retailer or local council recycling point", "Burning it in the garden", "Burying it in a field"], answer: 1, why: "Authorised take-back routes are required." },
        { q: "WEEE applies to…", options: ["Only mobile phones", "Only fridges", "Almost all electrical and electronic equipment", "Only laptops"], answer: 2, why: "Broad scope across categories." },
        { q: "True/False: WEEE encourages recovery of valuable components from old electronics.", options: ["True", "False"], answer: 0, why: "Recovery reduces fresh mining and conserves resources." },
        { q: "The overall outcome WEEE aims for is…", options: ["More landfill use", "Safer disposal + resource recovery + less harm", "Faster phone releases", "Cheaper raw mining"], answer: 1, why: "Environmental protection through structured recycling." },
      ],
    },
    {
      id: "recycling",
      code: "05",
      title: "Responsible Recycling",
      explanation:
        "Responsible recycling recovers valuable materials, prevents pollution and reduces the need to mine new resources. It conserves resources and reduces pollution at every stage.",
      bullets: [
        "Reduces chemical leakage into soil and water.",
        "Lowers landfill fire risks (lithium batteries can ignite).",
        "Recovers valuable metals such as gold, copper and aluminium.",
        "Reduces the need for fresh mining.",
        "Allows plastics to be recycled instead of decomposing into harmful toxic particles.",
        "Reduces toxic air pollution from burning waste.",
      ],
      paragraphs: [
        "Modern recycling plants can recover precious metals at higher purity than fresh mining. A single tonne of phones contains more gold than a tonne of typical gold ore.",
        "Without responsible recycling, plastics from devices slowly break down into microplastics that enter the food chain. Burning them releases dioxins and other toxic gases into the air, harming people and wildlife.",
      ],
      quiz: [
        { q: "How does responsible recycling reduce the need for fresh mining?", options: ["By recovering and reusing valuable metals from old devices", "By banning all electronics", "By printing new metals", "By cooling the planet"], answer: 0, why: "Recovered gold, copper, aluminium re-enter the supply chain." },
        { q: "Which is NOT a benefit of responsible recycling?", options: ["Less chemical leakage into soil and water", "Recovery of valuable metals", "More landfill use", "Lower landfill fire risk"], answer: 2, why: "Recycling DIVERTS material away from landfill." },
        { q: "Why are lithium batteries especially dangerous in landfill sites?", options: ["They are radioactive", "They can ignite and start landfill fires", "They explode in sunlight", "They magnetise nearby waste"], answer: 1, why: "Damaged lithium cells are a major landfill fire cause." },
        { q: "Which valuable metals are commonly recovered through e-waste recycling?", options: ["Gold, copper and aluminium", "Only mercury", "Only iron", "Only silicon"], answer: 0, why: "Phones contain more gold per tonne than typical gold ore." },
        { q: "Plastics in landfill from e-waste typically…", options: ["Decompose safely into soil", "Break down into harmful toxic microplastic particles", "Turn into wood", "Improve plant growth"], answer: 1, why: "Microplastics + leached additives enter ecosystems." },
        { q: "Burning e-waste informally releases…", options: ["Clean water", "Toxic air pollution including dioxins and heavy metals", "Drinkable air", "Solar panels"], answer: 1, why: "Cable burning is a major source of toxic fumes." },
        { q: "Recovered metals from recycling can be…", options: ["Re-used in new electronics", "Buried again immediately", "Only stored forever", "Only thrown away"], answer: 0, why: "Re-entering production = circular economy." },
        { q: "True/False: responsible recycling reduces toxic chemical leakage into the environment.", options: ["True", "False"], answer: 0, why: "Hazardous components are isolated and processed safely." },
        { q: "Compared with fresh mining, recycling existing devices is…", options: ["Much more destructive", "Generally less environmentally damaging", "Identical in impact", "Always more expensive"], answer: 1, why: "Lower energy + lower ecological cost overall." },
        { q: "A 'closed-loop' product lifecycle means…", options: ["One-time use only", "Materials are reused repeatedly with minimal waste", "Recycling is banned", "Mining is doubled"], answer: 1, why: "Circular economy principle." },
      ],
    },
    {
      id: "cycle",
      code: "06",
      title: "Short Replacement Cycle",
      explanation:
        "Most users replace mobile phones roughly every 3 years. The same is true of tablets, smart watches and laptops. This short cycle is encouraged by both consumer desire and manufacturer design choices — sometimes called planned obsolescence.",
      bullets: [
        "Mobile phones are replaced roughly every 3 years on average.",
        "Tablets, smart watches and laptops follow similar short cycles.",
        "Main cause: people want the newest technology models.",
        "Manufacturers embed batteries that are difficult to replace.",
        "Components are glued or soldered, making repair hard.",
        "Spare parts are expensive.",
        "Software and security updates are often stopped after a few years.",
        "Planned obsolescence = deliberately designing products to have a short useful life.",
      ],
      paragraphs: [
        "Embedded batteries, glued screens and soldered storage all push owners toward replacement instead of repair. When the battery weakens after 2–3 years, replacing it costs nearly as much as a new device.",
        "When manufacturers stop providing security updates, older devices become unsafe to use online — even if the hardware still works perfectly. This is one of the most powerful drivers of replacement.",
      ],
      quiz: [
        { q: "On average, how often is a mobile phone replaced?", options: ["Every 3 months", "Every 3 years", "Every 10 years", "Every 20 years"], answer: 1, why: "Roughly 3 years — same for tablets, smartwatches, laptops." },
        { q: "What is the MAIN consumer-driven cause of the short replacement cycle?", options: ["People wanting the newest technology and features", "Phones spontaneously exploding", "Schools banning older models", "Wi-Fi blocking old phones"], answer: 0, why: "Desire for the 'latest' drives churn." },
        { q: "Why do embedded batteries shorten device lifespan?", options: ["They cannot be easily replaced when they wear out", "They charge faster", "They last forever", "They reduce e-waste"], answer: 0, why: "Sealed batteries push owners to replace the whole device." },
        { q: "Planned obsolescence is best defined as…", options: ["Free upgrades forever", "Deliberately designing products to have a short useful life", "Permanent hardware", "Faster recycling"], answer: 1, why: "Spec definition of planned obsolescence." },
        { q: "Why does ending software / security updates increase e-waste?", options: ["Older devices become unsafe online and users replace them even if hardware works", "Old devices physically break", "Updates use no energy", "It cleans batteries"], answer: 0, why: "Security cut-off is a major driver of replacement." },
        { q: "Which manufacturer design choice makes repair harder?", options: ["Cheap replaceable screws", "Glued or soldered components and expensive spare parts", "Modular components", "Open repair manuals"], answer: 1, why: "Anti-repair design protects new sales." },
        { q: "A short replacement cycle leads to…", options: ["Less mining and energy use", "More e-waste, more mining and more energy demand", "Cleaner rivers", "Fewer factories"], answer: 1, why: "Higher churn = higher footprint." },
        { q: "True/False: limited spare parts availability encourages users to replace rather than repair.", options: ["True", "False"], answer: 0, why: "If a part costs nearly as much as a new device, buying new wins." },
        { q: "Which item is NOT typically replaced on a ~3-year cycle?", options: ["Smartphones", "Tablets", "Smartwatches", "Bricks"], answer: 3, why: "Spec lists phones, tablets, smartwatches, laptops." },
        { q: "Manufacturers often profit MORE from…", options: ["Encouraging long-life repair", "Encouraging replacement with new models", "Donating old devices", "Composting batteries"], answer: 1, why: "Replacement = revenue." },
      ],
    },
    {
      id: "ownership",
      code: "07",
      title: "Responsible Ownership",
      explanation:
        "Users can reduce environmental impact through responsible ownership. Every device kept longer or reused is one less mined, manufactured, shipped and discarded.",
      bullets: [
        "Keeping devices for longer reduces demand for new ones.",
        "Buying second-hand devices reuses existing hardware.",
        "Donating devices extends their useful life.",
        "Recycling properly through WEEE channels keeps toxins out of landfill.",
        "Reducing internet usage cuts data-centre and network energy.",
        "Using energy-efficiency settings lowers power draw.",
      ],
      paragraphs: [
        "Responsible ownership flips the script on planned obsolescence. By treating devices as long-term tools rather than fashion accessories, users directly cut mining, manufacturing energy and e-waste.",
        "Donating still-working devices to charities or schools gives them a second life. Reducing internet streaming quality, closing unused tabs and lowering brightness all cut energy at scale when millions of users do it.",
      ],
      quiz: [
        { q: "Which user action BEST reduces lifetime environmental impact?", options: ["Replacing devices every year", "Keeping devices in use for as long as possible", "Burning old phones", "Burying devices in the garden"], answer: 1, why: "Avoids new manufacture, the biggest footprint phase." },
        { q: "Buying a second-hand device instead of new mainly…", options: ["Wastes more resources", "Reuses existing hardware and avoids new mining + manufacture", "Increases mining demand", "Is illegal"], answer: 1, why: "Reuse extends an already-made device's life." },
        { q: "Donating a working old phone to charity…", options: ["Helps the environment AND another user", "Causes more pollution", "Is illegal", "Wastes the device"], answer: 0, why: "Extends useful life and reduces e-waste." },
        { q: "'Recycling responsibly' means…", options: ["Dropping it in any bin", "Using WEEE / authorised take-back channels", "Burning it at home", "Burying it secretly"], answer: 1, why: "Authorised routes ensure safe processing." },
        { q: "Reducing how much you stream / download cuts energy use in…", options: ["Only your phone", "Data centres, telecoms networks and devices", "Only your TV", "Nothing"], answer: 1, why: "Whole delivery chain consumes power per byte streamed." },
        { q: "Using energy-efficiency settings on a phone…", options: ["Lowers power draw and extends battery life", "Increases power use", "Damages the device", "Has no effect"], answer: 0, why: "Settings reduce consumption directly." },
        { q: "Which scenario shows responsible ownership?", options: ["Upgrading yearly for fashion", "Replacing the battery instead of buying a new phone", "Throwing the old phone in landfill", "Buying multiple devices a year"], answer: 1, why: "Repair before replace." },
        { q: "Responsible ownership directly counters…", options: ["Healthy soil", "Planned obsolescence", "Recycling", "WEEE"], answer: 1, why: "Keeping devices longer defeats the short-cycle model." },
        { q: "Keeping devices longer leads to…", options: ["Less mining and less manufacturing energy", "More e-waste immediately", "More pollution always", "More mining"], answer: 0, why: "Avoids replacement-driven production." },
        { q: "True/False: small individual choices, multiplied across billions of users, create large global impact.", options: ["True", "False"], answer: 0, why: "Scale turns small savings into major reductions." },
      ],
    },
    {
      id: "reduce",
      code: "08",
      title: "Reducing Energy Consumption",
      explanation:
        "There are many practical ways to cut the energy used by digital devices. Each method either lowers the device's power draw, switches off unused features, or moves consumption to cleaner sources.",
      bullets: [
        "Lowering screen brightness — display is the biggest battery drain.",
        "Sleep mode — cuts power when idle.",
        "Turning off Bluetooth — stops radio scanning.",
        "Disabling Wi-Fi when not needed — saves continuous radio activity.",
        "Disabling GPS — location tracking is energy-hungry.",
        "Closing dormant applications — they consume CPU and RAM in the background.",
        "Disconnecting peripherals — USB devices, external drives and chargers draw power.",
        "Buying energy-efficient devices (lower TDP, efficient SoCs).",
        "Choosing services hosted in renewable-energy data centres.",
      ],
      paragraphs: [
        "Screens dominate device energy use; halving brightness can nearly double battery life. Disabling radios (Wi-Fi, Bluetooth, GPS) cuts background scanning that runs even when the screen is off.",
        "Dormant apps continue to fetch data, sync and run timers. Closing them, or denying background access, removes hidden energy drain. At a larger scale, choosing cloud services that run on renewable-powered data centres shifts the underlying grid demand toward clean sources.",
      ],
      quiz: [
        { q: "Which device component is usually the BIGGEST drain on battery?", options: ["The display screen", "The plastic case", "The brand logo", "The SIM card"], answer: 0, why: "Display dominates phone/laptop energy use." },
        { q: "Sleep mode reduces energy use by…", options: ["Increasing CPU activity", "Cutting power to non-essential components when idle", "Raising brightness", "Disabling encryption"], answer: 1, why: "Idle systems draw minimum power." },
        { q: "Turning off Bluetooth saves energy because…", options: ["It stops continuous radio scanning for devices", "It removes installed apps", "It cools the CPU directly", "It deletes user files"], answer: 0, why: "Bluetooth scans continuously when on." },
        { q: "Why does disabling GPS reduce battery drain?", options: ["GPS location tracking is energy-hungry", "GPS uses no power", "GPS damages RAM", "GPS locks the phone"], answer: 0, why: "Constant satellite + sensor polling consumes power." },
        { q: "Closing dormant background applications…", options: ["Frees CPU/RAM and stops hidden energy drain", "Wastes more energy", "Reformats the SSD", "Has no effect"], answer: 0, why: "Background sync/timers stop." },
        { q: "Disconnecting unused peripherals (USB drives, chargers)…", options: ["Stops unnecessary power draw", "Increases device draw", "Damages the device", "Is illegal"], answer: 0, why: "Connected USB devices continue drawing power." },
        { q: "An 'energy-efficient' device is one that…", options: ["Delivers the same performance using less power", "Uses more fans", "Has bigger plugs", "Generates more heat"], answer: 0, why: "Better performance per watt." },
        { q: "Choosing services hosted in renewable-powered data centres…", options: ["Shifts demand to cleaner energy sources", "Burns more coal", "Uses no energy", "Is forbidden"], answer: 0, why: "Reduces grid carbon intensity." },
        { q: "Lowering screen brightness from 100% to 50% typically…", options: ["Saves substantial battery and energy", "Damages the screen", "Disables Wi-Fi", "Reduces RAM"], answer: 0, why: "Display power scales with brightness." },
        { q: "Which combination would MOST reduce a phone's daily energy use?", options: ["Max brightness + Bluetooth on + GPS on", "Sleep mode + lower brightness + Wi-Fi/Bluetooth/GPS off when not needed", "Always streaming HD video", "Charging continuously"], answer: 1, why: "Layered energy-saving choices." },
      ],
    },
    {
      id: "positive",
      code: "09",
      title: "Positive Environmental Impact",
      explanation:
        "Technology creates environmental problems but it can also solve them. Intelligent systems, monitoring tools and automation can cut waste, reduce emissions and protect wildlife at a scale impossible by hand.",
      bullets: [
        "Intelligent traffic systems reduce congestion and fuel use.",
        "Smart lighting systems lower electricity demand in cities.",
        "Environmental monitoring systems track pollution, deforestation and climate.",
        "Anti-poaching monitoring protects endangered wildlife.",
        "Regulation enforcement systems detect illegal dumping and emissions.",
      ],
      paragraphs: [
        "Smart traffic lights adapt to real-time flow, reducing the time cars sit idling at red lights — directly cutting urban pollution. Smart city lighting dims when streets are empty and brightens on demand.",
        "Sensor networks and satellite imaging now monitor rainforests, oceans and air quality across the planet. AI-powered cameras in national parks alert rangers to suspected poachers in real time, helping protect endangered species.",
      ],
      quiz: [
        { q: "How do intelligent traffic systems benefit the environment?", options: ["By increasing congestion", "By adapting signals to real-time flow, reducing idling and fuel use", "By banning all cars", "By slowing traffic deliberately"], answer: 1, why: "Smart signals cut wasted fuel at junctions." },
        { q: "Smart street-lighting reduces energy by…", options: ["Running at max brightness always", "Dimming or switching off when no activity is detected", "Burning fuel directly", "Removing all sensors"], answer: 1, why: "Demand-responsive lighting saves power." },
        { q: "Environmental monitoring systems use sensors and satellites to track…", options: ["Pollution levels, deforestation and climate change", "TV ratings", "Sports scores", "Music charts"], answer: 0, why: "Continuous environmental data collection." },
        { q: "Anti-poaching technology typically protects wildlife by…", options: ["Alerting rangers via AI cameras / motion sensors in real time", "Removing all animals", "Building roads in parks", "Banning rangers"], answer: 0, why: "Real-time detection of intruders helps protect species." },
        { q: "Regulation enforcement systems can use technology to…", options: ["Detect illegal dumping and emissions automatically", "Ban all factories", "Plant trees themselves", "Cool the planet directly"], answer: 0, why: "Sensors + AI flag breaches for human enforcement." },
        { q: "Which statement is most accurate?", options: ["Technology only harms the environment", "Technology can both harm AND help — outcome depends on how it is used", "Technology has no impact", "Technology is always green"], answer: 1, why: "Double-edged tool — design and policy matter." },
        { q: "True/False: AI-powered cameras can identify and alert rangers to suspected poachers.", options: ["True", "False"], answer: 0, why: "Already deployed in several national parks." },
        { q: "Smart electricity grids help by…", options: ["Balancing renewable supply against real-time demand", "Disabling all renewables", "Forcing constant peak demand", "Ignoring usage data"], answer: 0, why: "Grid balancing enables higher renewables share." },
        { q: "Cars idling at traditional traffic lights produce…", options: ["More CO₂ and local air pollution", "Cleaner air", "Free electricity", "Less noise"], answer: 0, why: "Idle = wasted fuel = emissions." },
        { q: "The best one-line summary of technology's environmental role is…", options: ["A pure villain", "A neutral tool whose impact depends on how humans use it", "Completely useless", "Always perfectly green"], answer: 1, why: "Impact is design + policy driven." },
      ],
    },
  ],
  flashcards: [
    { category: "MANUFACTURE", front: "Raw materials in devices", back: "Copper, palladium (non-renewable) and arsenic (highly toxic)." },
    { category: "MANUFACTURE", front: "Mining damage", back: "Scars landscapes, creates waste, destroys habitats, damages ecosystems, pollutes." },
    { category: "MANUFACTURE", front: "Manufacturing energy", back: "Huge amounts, mostly from fossil fuels → CO₂ → climate change." },
    { category: "MANUFACTURE", front: "Waste water", back: "Polluted with toxic chemicals; can enter rivers/lakes and damage ecosystems." },
    { category: "ENERGY", front: "70/30 split", back: "Manufacture + disposal ≈ 70% of lifetime energy; use ≈ 30%." },
    { category: "ENERGY", front: "Where energy goes", back: "Production, operation, online storage in data centres, recycling, telecoms networks." },
    { category: "ENERGY", front: "Tech that saves energy", back: "Smart lighting, route planners, light sensors, intelligent systems." },
    { category: "DISPOSAL", front: "E-waste stats", back: "~50 Mt/year globally, only ~20% recycled." },
    { category: "DISPOSAL", front: "Toxic leaks", back: "Lead, mercury, cobalt → soil, groundwater, rivers." },
    { category: "DISPOSAL", front: "Health impact", back: "Poisoning, disease, long-term health problems near dump sites." },
    { category: "WEEE", front: "WEEE meaning", back: "Waste Electrical and Electronic Equipment regulations." },
    { category: "WEEE", front: "WEEE purpose", back: "Set recycling and collection targets, encourage recovery, reduce e-waste harm." },
    { category: "RECYCLING", front: "Recycling benefits", back: "Less chemical leak, lower fire risk, recover metals, less mining, recycle plastics, less air pollution." },
    { category: "REPLACEMENT", front: "Replacement cycle", back: "~3 years for phones; same for tablets, smartwatches, laptops." },
    { category: "REPLACEMENT", front: "Planned obsolescence", back: "Embedded batteries, glued/soldered parts, expensive spares, limited updates." },
    { category: "OWNERSHIP", front: "Responsible ownership", back: "Keep longer, buy second-hand, donate, recycle, reduce internet use, energy-efficient settings." },
    { category: "REDUCE", front: "Energy-saving actions", back: "Lower brightness, sleep mode, off Bluetooth/Wi-Fi/GPS, close apps, disconnect peripherals, efficient devices, renewable data centres." },
    { category: "POSITIVE", front: "Tech helping environment", back: "Smart traffic, smart lighting, environmental + anti-poaching monitoring, enforcement systems." },
  ],
};
