import type { TopicContent } from "./types";

export const environmentalIssues: TopicContent = {
  slug: "environmental-issues",
  hero:
    "Every device on Earth has a hidden cost — from the mines where its metals are dug, to the factories that assemble it, to the landfill it eventually rots in. This module decodes the full environmental footprint of computing and what operators can do about it.",
  tags: ["MANUFACTURE", "ENERGY", "DISPOSAL", "WEEE", "RECYCLING", "REPLACEMENT", "REDUCE", "POSITIVE"],
  sections: [
    {
      id: "manufacture",
      code: "01",
      title: "Manufacture",
      explanation:
        "Producing a digital device requires huge amounts of raw materials, energy, and water — long before it is ever switched on. The environmental cost of a phone or laptop begins inside a mine.",
      bullets: [
        "Devices need raw materials such as copper, palladium and arsenic.",
        "Copper and palladium are non-renewable — once used, they are gone for centuries.",
        "Arsenic is highly toxic and must be handled carefully.",
        "Mining scars landscapes, destroys wildlife habitats and pollutes nearby ecosystems.",
        "Manufacturing uses huge amounts of energy, often from fossil fuels.",
        "Burning fossil fuels releases CO₂, accelerating global warming and climate change.",
        "Factories produce polluted waste water containing toxic chemicals.",
      ],
      paragraphs: [
        "Mining for the metals inside a phone strips topsoil, diverts rivers and leaves behind huge open pits. Local wildlife loses its habitat and the surrounding communities often lose access to clean water.",
        "Silicon chips are produced in cleanrooms that need vast amounts of ultra-pure water and electricity. A single chip factory can use as much power as a small city, and most of that electricity still comes from non-renewable fossil fuels.",
        "Waste water from chip plants and metal refineries can contain heavy metals and solvents. If it is not treated properly it leaks into rivers and lakes, killing fish and contaminating drinking water for years afterwards.",
      ],
      quiz: [
        { q: "Which raw material used in devices is highly toxic?", options: ["Copper", "Palladium", "Arsenic", "Aluminium"], answer: 2, why: "Arsenic is toxic and dangerous to handle during manufacture." },
        { q: "Why is copper described as non-renewable?", options: ["It rusts away", "Earth has a finite supply that cannot regrow", "It is illegal to mine", "It evaporates"], answer: 1, why: "Non-renewable means there is a finite supply that nature cannot replace quickly." },
        { q: "Mining for materials mainly damages…", options: ["The internet", "Wildlife habitats and ecosystems", "Software performance", "Server uptime"], answer: 1, why: "Strip mining destroys land and the species that live there." },
        { q: "Most electricity used in manufacturing comes from…", options: ["Solar only", "Wind only", "Fossil fuels", "Nuclear only"], answer: 2, why: "Most global electricity is still produced by burning fossil fuels." },
        { q: "Burning fossil fuels contributes to…", options: ["Faster Wi-Fi", "Climate change", "Cheaper devices", "Battery life"], answer: 1, why: "CO₂ from fossil fuels is a major driver of climate change." },
        { q: "Polluted waste water from factories can…", options: ["Improve ecosystems", "Damage rivers and lakes", "Make rain cleaner", "Cool the planet"], answer: 1, why: "Toxic chemicals can leak into ecosystems and cause long-term damage." },
        { q: "True or false: a phone has environmental costs even before it is switched on.", options: ["True", "False"], answer: 0, why: "Mining, manufacture and shipping all happen before the first power-on." },
        { q: "Which of these is NOT a typical manufacturing impact?", options: ["Energy use", "Toxic waste water", "Habitat loss", "Less e-waste"], answer: 3, why: "Manufacturing increases e-waste pressure, not reduces it." },
        { q: "Which best describes a non-renewable resource?", options: ["Always recyclable", "Regrows quickly", "Cannot be replaced fast enough once used", "Free to extract"], answer: 2, why: "Definition: cannot be replenished by nature on a useful timescale." },
        { q: "Why does mining ‘damage ecosystems’?", options: ["It removes habitats and pollutes water", "It plants more trees", "It feeds the animals", "It cools the climate"], answer: 0, why: "Mining removes vegetation and contaminates surrounding land and water." },
      ],
    },
    {
      id: "energy",
      code: "02",
      title: "Energy Consumption",
      explanation:
        "Digital technology is hungry for electricity at every stage: producing devices, using them, storing our data in the cloud, and recycling them at the end. Most of that energy is consumed away from the user.",
      bullets: [
        "Roughly 70% of a device's lifetime energy is used in manufacture and disposal.",
        "Only around 30% is used during actual use.",
        "Data centres run 24/7, storing and serving huge amounts of data.",
        "Telecom networks (cell masts, routers, undersea cables) consume continuous power.",
        "Cooling servers can use almost as much energy as the servers themselves.",
        "Smart systems, sensors and route planners can REDUCE energy use elsewhere.",
      ],
      paragraphs: [
        "When you stream a video, the energy is not just in your phone — it's in the data centre serving the video, the network carrying it, and the cooling system stopping the servers from melting. The visible part is tiny compared to the hidden infrastructure.",
        "Manufacture + transport + recycling typically account for the majority of a device's total energy footprint. This is why keeping a device longer is often greener than upgrading to a 'more efficient' new one.",
        "Technology can also CUT energy elsewhere. Smart lighting turns off empty rooms, route planners reduce wasted fuel, and intelligent grids balance renewable supply and demand.",
      ],
      quiz: [
        { q: "Roughly what % of a device's lifetime energy is used in manufacture and disposal?", options: ["10%", "30%", "70%", "90%"], answer: 2, why: "About 70% — most energy is used outside the actual usage phase." },
        { q: "Which part of a data centre uses huge amounts of energy alongside the servers?", options: ["Door handles", "Cooling systems", "Wi-Fi sticker", "Reception desk"], answer: 1, why: "Cooling is one of the biggest costs of running a data centre." },
        { q: "Data centres are mostly…", options: ["Off at night", "Powered down on weekends", "Running 24/7", "Solar-only"], answer: 2, why: "They must stay online continuously to serve global users." },
        { q: "Which of these REDUCES energy use through technology?", options: ["Smart lighting", "Bigger screens", "Brighter displays", "Always-on GPS"], answer: 0, why: "Smart lighting only powers rooms when needed." },
        { q: "Route planners can help the environment by…", options: ["Adding traffic", "Reducing wasted fuel", "Burning more petrol", "Stopping deliveries"], answer: 1, why: "Better routes mean less fuel burned." },
        { q: "Most data centre energy currently comes from…", options: ["100% renewables", "A mix, often still including fossil fuels", "Hydrogen", "Pedal power"], answer: 1, why: "Many centres still rely on grids that include fossil fuels." },
        { q: "Why is 'use' only ~30% of energy footprint?", options: ["Devices barely use power", "Manufacture and disposal dominate", "Charging is free", "Software is light"], answer: 1, why: "Production and end-of-life dominate the lifetime total." },
        { q: "Which is an intelligent system that reduces waste?", options: ["Random street lights", "Light sensors that turn off unused lights", "Faulty AC", "Always-on heating"], answer: 1, why: "Sensors prevent wasted electricity." },
        { q: "Which uses continuous power around the world?", options: ["Telecom networks", "School bells", "Calculators", "Pens"], answer: 0, why: "Cell masts, switches and undersea cables run 24/7." },
        { q: "True/False: streaming HD video uses zero energy outside your phone.", options: ["True", "False"], answer: 1, why: "It also uses the data centre, network, and cooling systems." },
      ],
    },
    {
      id: "disposal",
      code: "03",
      title: "Disposal & E-waste",
      explanation:
        "Discarded digital devices become e-waste. The world produces around 50 million tonnes of it every year, and only roughly 20% is properly recycled.",
      bullets: [
        "~50 million tonnes of e-waste produced globally per year.",
        "Only around 20% is recycled responsibly.",
        "Illegal dumping leaks lead, mercury and cobalt into soil and groundwater.",
        "Chemicals enter rivers and contaminate drinking water.",
        "People near dumpsites suffer poisoning, disease and long-term health problems.",
        "Millions of tonnes are shipped to developing countries to be salvaged unsafely.",
      ],
      paragraphs: [
        "Many electronics are dumped illegally in landfill sites in poorer countries. Local workers — sometimes children — burn cables to recover copper, exposing themselves to highly toxic fumes.",
        "Heavy metals such as lead, mercury and cobalt leak slowly into the soil. Once in the groundwater they are extremely difficult to remove and can poison drinking water for entire communities.",
        "Long-term exposure causes serious illness, including neurological damage and cancers. The environmental and human cost of careless disposal is enormous compared to the small effort of recycling responsibly.",
      ],
      quiz: [
        { q: "Approximately how much e-waste is produced globally each year?", options: ["5 Mt", "20 Mt", "50 Mt", "500 Mt"], answer: 2, why: "Around 50 million tonnes annually." },
        { q: "Roughly what percentage is properly recycled?", options: ["20%", "50%", "75%", "95%"], answer: 0, why: "Only about 20% is recycled responsibly." },
        { q: "Which chemicals commonly leak from e-waste?", options: ["Sugar and salt", "Lead, mercury, cobalt", "Oxygen and nitrogen", "Iron and zinc only"], answer: 1, why: "These heavy metals are toxic and persistent." },
        { q: "Where does e-waste contamination often end up?", options: ["The cloud", "Soil and groundwater", "Outer space", "Books"], answer: 1, why: "Toxic chemicals leach into the ground and water table." },
        { q: "Communities near dumpsites often suffer…", options: ["Better internet", "Poisoning and disease", "Cheaper bills", "Cleaner water"], answer: 1, why: "Long-term exposure causes serious health problems." },
        { q: "Why do people salvage e-waste in poorer countries?", options: ["It is safe and fun", "To recover valuable materials, despite the danger", "Government forces them", "Schools require it"], answer: 1, why: "Poverty drives unsafe salvage for valuable metals." },
        { q: "Which is NOT a consequence of illegal dumping?", options: ["Soil pollution", "Water contamination", "Improved biodiversity", "Health problems"], answer: 2, why: "Illegal dumping reduces biodiversity, it does not improve it." },
        { q: "True/False: e-waste decomposes safely like food waste.", options: ["True", "False"], answer: 1, why: "Electronics contain non-biodegradable, toxic components." },
        { q: "Millions of tonnes of e-waste are exported to…", options: ["The moon", "Developing countries", "The deep sea only", "Nowhere"], answer: 1, why: "Wealthier nations often ship waste abroad." },
        { q: "Which best describes 'e-waste'?", options: ["Spam emails", "Discarded electronic devices", "Old PDF files", "Used USB cables only"], answer: 1, why: "E-waste = any discarded electrical / electronic equipment." },
      ],
    },
    {
      id: "weee",
      code: "04",
      title: "WEEE Regulations",
      explanation:
        "The WEEE regulations (Waste Electrical and Electronic Equipment) are designed to reduce environmental harm from discarded electronics by forcing producers and retailers to collect and recycle them properly.",
      bullets: [
        "WEEE = Waste Electrical and Electronic Equipment.",
        "Sets legal recycling and collection targets.",
        "Encourages recovery of valuable electronic components.",
        "Aims to reduce environmental harm caused by e-waste.",
        "Retailers must offer take-back schemes for old equipment.",
      ],
      paragraphs: [
        "Before WEEE, manufacturers had no real responsibility for what happened to a product after it was sold. The regulations force them to fund proper collection and recycling, putting the cost where it belongs.",
        "Targets are set for the proportion of electronics that must be collected and recycled each year. Failing to meet them carries large fines, so producers actively support recycling networks.",
      ],
      quiz: [
        { q: "WEEE stands for…", options: ["World Electrical Energy Exchange", "Waste Electrical and Electronic Equipment", "Wireless Edge Electronics Effort", "Web Electronic Engineering Ethics"], answer: 1, why: "Definition from the regulations." },
        { q: "WEEE sets targets for…", options: ["Mining new metals", "Recycling and collection of electronics", "Game design", "Marketing budgets"], answer: 1, why: "Collection and recycling targets are central." },
        { q: "WEEE encourages…", options: ["Quick dumping", "Recovery of electronics", "Illegal export", "Burning waste"], answer: 1, why: "Recovery and reuse are key goals." },
        { q: "Main purpose of WEEE?", options: ["Help advertisers", "Reduce environmental harm of e-waste", "Speed up Wi-Fi", "Lower phone prices"], answer: 1, why: "Stated purpose of the regulations." },
        { q: "True/False: WEEE puts no responsibility on producers.", options: ["True", "False"], answer: 1, why: "It places legal responsibility on producers and retailers." },
        { q: "Retailers are required to…", options: ["Refuse old electronics", "Offer take-back of old equipment", "Burn old phones", "Send waste to landfill"], answer: 1, why: "Take-back schemes are part of WEEE." },
        { q: "What happens if targets are missed?", options: ["Nothing", "Producers can be fined", "Customers go to prison", "Devices get cheaper"], answer: 1, why: "Penalties drive compliance." },
        { q: "WEEE applies to…", options: ["Only fridges", "Electrical and electronic equipment", "Only mobile phones", "Books"], answer: 1, why: "Broad scope of electrical/electronic items." },
        { q: "WEEE is best described as a…", options: ["Game", "Set of regulations", "Phone brand", "Recycling logo only"], answer: 1, why: "It is a regulatory framework." },
        { q: "WEEE helps achieve…", options: ["More mining", "More e-waste in landfill", "Safer disposal and resource recovery", "Faster batteries"], answer: 2, why: "Goal: safer recycling and reduced harm." },
      ],
    },
    {
      id: "recycling",
      code: "05",
      title: "Responsible Recycling",
      explanation:
        "Responsible recycling recovers valuable materials, prevents pollution and reduces the need to mine new resources. Done properly, it closes the loop on the device lifecycle.",
      bullets: [
        "Reduces chemical leakage into soil and water.",
        "Lowers landfill fire risks (lithium batteries are flammable).",
        "Recovers valuable metals such as gold, copper and aluminium.",
        "Reduces the need for fresh mining.",
        "Allows plastics to be recycled instead of decomposing into toxic particles.",
        "Reduces toxic air pollution from burning waste.",
      ],
      paragraphs: [
        "Modern recycling plants can recover precious metals at higher purity than fresh mining. A single tonne of phones contains far more gold than a tonne of typical ore.",
        "Without responsible recycling, plastics from devices slowly break down into microplastics that enter the food chain. Burning them releases dioxins and other toxic gases into the air.",
      ],
      quiz: [
        { q: "Responsible recycling helps reduce…", options: ["Mining demand", "Internet speed", "Cricket scores", "Battery sizes"], answer: 0, why: "Recovered metals reduce the need for new mining." },
        { q: "Which is NOT a benefit of recycling?", options: ["Less pollution", "Resource recovery", "More landfill use", "Lower fire risk"], answer: 2, why: "Recycling reduces landfill, not increases it." },
        { q: "Why are lithium batteries dangerous in landfill?", options: ["They are radioactive", "They can catch fire", "They explode in sunlight", "They are magnetic"], answer: 1, why: "Damaged lithium cells can ignite and burn." },
        { q: "Which metals are commonly recovered from e-waste?", options: ["Gold, copper, aluminium", "Mercury and lead only", "Silicon only", "Iron only"], answer: 0, why: "Precious and base metals are recovered." },
        { q: "Plastics from devices in landfill can…", options: ["Decompose safely", "Decompose into toxic particles", "Turn into wood", "Boost soil quality"], answer: 1, why: "They break down into harmful microplastics." },
        { q: "Burning e-waste produces…", options: ["Fresh air", "Toxic air pollution", "Drinking water", "Solar panels"], answer: 1, why: "Burning releases dioxins and heavy metals." },
        { q: "Recovered metals can be…", options: ["Only sold abroad", "Reused in new electronics", "Buried again", "Eaten safely"], answer: 1, why: "They re-enter the manufacturing supply chain." },
        { q: "True/False: recycling reduces toxic chemical leakage.", options: ["True", "False"], answer: 0, why: "Proper processing keeps toxins out of nature." },
        { q: "Compared with mining new metals, recycling is…", options: ["More destructive", "Less environmentally damaging", "Identical", "Always more expensive"], answer: 1, why: "Recycling typically has a far lower footprint." },
        { q: "A 'closed loop' lifecycle means…", options: ["Wasting more", "Reusing materials repeatedly", "One-time use only", "No recycling at all"], answer: 1, why: "Materials cycle back into production." },
      ],
    },
    {
      id: "cycle",
      code: "06",
      title: "Short Replacement Cycle",
      explanation:
        "Most users replace mobile phones, tablets, smart watches and laptops roughly every 3 years. This short cycle is not accidental — it is encouraged by manufacturer design choices and marketing.",
      bullets: [
        "Average mobile phone replacement is around every 3 years.",
        "Tablets, smartwatches and laptops follow similar short cycles.",
        "Users want the newest models with the latest features.",
        "Manufacturers embed batteries that are difficult to replace.",
        "Components are glued or soldered, making repair hard.",
        "Spare parts are expensive and software/security updates often stop.",
        "This is known as 'planned obsolescence'.",
      ],
      paragraphs: [
        "When a battery is glued in or a screen is fused to the body, repair becomes more expensive than buying a new device. Users feel they have 'no choice' but to upgrade — which is exactly what the manufacturer wants.",
        "Withdrawing software updates after a few years is one of the strongest drivers of replacement. Even hardware that still works perfectly becomes insecure and slow when its operating system is no longer supported.",
        "Planned obsolescence is the deliberate design of products with a limited useful life. It guarantees a future stream of sales — and a future stream of e-waste.",
      ],
      quiz: [
        { q: "Average mobile phone replacement happens roughly every…", options: ["6 months", "3 years", "10 years", "20 years"], answer: 1, why: "Around 3 years is typical." },
        { q: "Planned obsolescence means…", options: ["Random hardware failure", "Designing products to have a limited life", "Free upgrades for life", "Government rules"], answer: 1, why: "Deliberate short useful life." },
        { q: "Which makes repair harder?", options: ["Easy-open screws", "Glued and soldered parts", "Free repair manuals", "Modular design"], answer: 1, why: "Glue/solder block easy replacement." },
        { q: "Which is NOT a typical short-cycle driver?", options: ["Embedded battery", "Withdrawal of software updates", "Cheap spare parts", "Marketing pressure"], answer: 2, why: "Spare parts are usually expensive, not cheap." },
        { q: "Why does losing software updates push replacement?", options: ["It makes the device faster", "Older OS becomes insecure and unsupported", "It changes the colour", "It refunds the buyer"], answer: 1, why: "Security and compatibility decay force upgrades." },
        { q: "Which devices share this short cycle?", options: ["Only phones", "Phones, tablets, laptops, smartwatches", "Only fridges", "Only desktops"], answer: 1, why: "Many personal electronics follow the same trend." },
        { q: "Marketing's role is to…", options: ["Discourage upgrades", "Make the newest model feel essential", "Hide product launches", "Refund old devices"], answer: 1, why: "Adverts create perceived need." },
        { q: "True/False: glued batteries are intended to make repair easier.", options: ["True", "False"], answer: 1, why: "They make repair much harder." },
        { q: "Planned obsolescence guarantees…", options: ["Less e-waste", "Future repeat sales", "Free recycling", "Universal repairability"], answer: 1, why: "Repeat sales are the financial goal." },
        { q: "What replaces the user's choice in 'no choice but to upgrade'?", options: ["Open repair markets", "Cost and difficulty of repair", "Government bans", "Network speed"], answer: 1, why: "Repair becomes uneconomical." },
      ],
    },
    {
      id: "consequences",
      code: "07",
      title: "Consequences & Responsible Ownership",
      explanation:
        "A short replacement cycle multiplies every environmental cost: more mining, more manufacturing energy, more shipping, more packaging and dramatically more e-waste. Responsible ownership pushes back against this.",
      bullets: [
        "More devices replaced → more e-waste.",
        "More mining and more manufacturing pollution.",
        "More transport emissions from global shipping.",
        "More energy consumed across the whole lifecycle.",
        "Responsible ownership: keep devices longer.",
        "Buy second-hand where possible.",
        "Donate working devices instead of binning them.",
        "Recycle properly via WEEE / take-back schemes.",
        "Reduce unnecessary streaming and downloads.",
        "Use built-in energy-efficiency settings.",
      ],
      paragraphs: [
        "Every replaced phone triggers a new mining and manufacturing cycle and adds another device to the e-waste pile. Multiplied across billions of users, the impact is enormous.",
        "Responsible ownership is the single most powerful thing an individual can do. Keeping a phone for 4 years instead of 2 nearly halves its lifetime environmental impact.",
      ],
      quiz: [
        { q: "Short replacement cycles increase…", options: ["E-waste", "Biodiversity", "Soil quality", "Battery lifespan"], answer: 0, why: "More replacements → more discarded devices." },
        { q: "Which is part of responsible ownership?", options: ["Buying every new model", "Keeping devices longer", "Throwing devices in general waste", "Hiding old phones"], answer: 1, why: "Longer life = lower impact." },
        { q: "Buying second-hand devices…", options: ["Increases mining", "Reduces demand for new manufacture", "Causes faster obsolescence", "Adds e-waste"], answer: 1, why: "Reuses existing manufactured goods." },
        { q: "Which is NOT a consequence of short cycles?", options: ["More mining", "More manufacturing", "More pollution", "Less energy use"], answer: 3, why: "Energy use rises, not falls." },
        { q: "Donating working devices means…", options: ["Less reuse", "Extending the life of working hardware", "Forced upgrades", "Banning recycling"], answer: 1, why: "It extends device life." },
        { q: "Reducing internet usage helps because…", options: ["It saves data centre energy", "It deletes files", "It removes adverts", "It charges batteries"], answer: 0, why: "Less data served = less server energy." },
        { q: "Energy-efficiency settings…", options: ["Drain the battery", "Reduce power draw", "Disable Wi-Fi forever", "Delete photos"], answer: 1, why: "They cut unnecessary consumption." },
        { q: "True/False: keeping a phone 4 years instead of 2 dramatically lowers impact.", options: ["True", "False"], answer: 0, why: "Manufacturing footprint is spread over more years." },
        { q: "Which is a 'donate' option for an old device?", options: ["School or charity", "Landfill", "Burn pile", "Ocean"], answer: 0, why: "Charities can reuse working devices." },
        { q: "What multiplies the impact of short cycles globally?", options: ["Billions of users following the pattern", "Just one country", "Only one factory", "Nothing"], answer: 0, why: "Scale across billions of devices is the real problem." },
      ],
    },
    {
      id: "reduce",
      code: "08",
      title: "Ways to Reduce Energy Consumption",
      explanation:
        "Users can dramatically cut a device's energy use through simple settings and habits. Each setting tackles a specific drain on the battery and the grid.",
      bullets: [
        "Lower screen brightness — the screen is one of the biggest power draws.",
        "Use sleep mode when stepping away briefly.",
        "Turn off Bluetooth when not in use.",
        "Disable Wi-Fi if you don't need it.",
        "Disable GPS when not navigating.",
        "Close dormant applications running in the background.",
        "Disconnect peripherals (USB drives, hubs) when idle.",
        "Buy energy-efficient devices in the first place.",
        "Choose data centres powered by renewable energy.",
      ],
      paragraphs: [
        "Each wireless radio (Wi-Fi, Bluetooth, GPS, mobile data) keeps scanning even when idle. Turning off ones you don't need stops that constant background drain.",
        "Background apps consume CPU cycles and refresh data over the network. Closing them or restricting their background activity gives the processor a real rest.",
        "When buying new hardware, the most energy-efficient model often pays for itself many times over the device's life.",
      ],
      quiz: [
        { q: "Which is one of the biggest power draws on a device?", options: ["Camera lens cover", "The screen", "The headphone jack", "The logo"], answer: 1, why: "Displays consume large amounts of power." },
        { q: "Sleep mode helps because it…", options: ["Boosts performance", "Suspends most components when idle", "Disables the OS forever", "Charges other phones"], answer: 1, why: "Components are paused until needed." },
        { q: "Why turn off GPS when not navigating?", options: ["It keeps scanning satellites and uses power", "It deletes maps", "It improves photos", "It removes ads"], answer: 0, why: "Continuous satellite lookups drain energy." },
        { q: "Closing dormant apps…", options: ["Frees CPU and battery", "Makes the device hotter", "Disables Wi-Fi forever", "Speeds up ageing"], answer: 0, why: "Reduces background load." },
        { q: "Choosing renewable-energy data centres…", options: ["Increases CO₂", "Lowers the carbon footprint of your data", "Has no effect", "Makes the cloud larger"], answer: 1, why: "Cleaner electricity = cleaner cloud usage." },
        { q: "Disconnecting peripherals helps because…", options: ["They draw power while connected", "They make Wi-Fi slower", "They cost money each second", "They prevent updates"], answer: 0, why: "Idle peripherals still draw current." },
        { q: "Which is NOT an energy-saving habit?", options: ["Disable Bluetooth when unused", "Lower brightness", "Stream 4K all night", "Use power-saver mode"], answer: 2, why: "Continuous streaming wastes large amounts of energy." },
        { q: "Energy-efficient devices…", options: ["Use more electricity", "Use less electricity for the same task", "Always cost less to buy", "Don't exist"], answer: 1, why: "Definition of energy-efficient." },
        { q: "True/False: turning off Wi-Fi when unused saves energy.", options: ["True", "False"], answer: 0, why: "It stops the radio from scanning constantly." },
        { q: "Why does brightness affect energy so much?", options: ["LEDs draw more power as they brighten", "Brightness is software-only", "It doesn't", "It only affects audio"], answer: 0, why: "Backlights and OLEDs scale power with brightness." },
      ],
    },
    {
      id: "positive",
      code: "09",
      title: "Positive Impact of Technology",
      explanation:
        "Technology causes environmental problems but can also solve them. Used wisely, the same systems that strain the planet can help protect it.",
      bullets: [
        "Intelligent traffic systems reduce congestion and fuel waste.",
        "Smart lighting cuts electricity use in homes and cities.",
        "Environmental monitoring tracks deforestation, pollution and wildlife.",
        "Anti-poaching systems use sensors and AI to protect endangered species.",
        "Regulation-enforcement systems detect illegal dumping and emissions.",
        "Smart grids balance supply and demand to maximise renewable energy.",
      ],
      paragraphs: [
        "Networks of satellites and ground sensors can detect illegal logging or oil spills within hours, allowing authorities to respond before the damage spreads.",
        "Anti-poaching teams use camera traps, drones and machine learning to alert rangers to intruders in protected reserves — a digital shield for wildlife.",
        "Smart grids predict when solar and wind output will peak, then shift demand (like charging electric cars) to match. This squeezes more value out of clean energy.",
      ],
      quiz: [
        { q: "Which is a positive environmental use of technology?", options: ["More mining drones", "Anti-poaching monitoring", "Streaming forever", "Disposable phones"], answer: 1, why: "AI + sensors help protect wildlife." },
        { q: "Smart traffic systems can reduce…", options: ["Internet ads", "Congestion and wasted fuel", "Phone battery life", "Wi-Fi speed"], answer: 1, why: "Better flow = less idling = less fuel burned." },
        { q: "Environmental monitoring uses…", options: ["Hand-written diaries", "Satellites and sensors", "Magic crystals", "Only paper maps"], answer: 1, why: "Remote sensing tracks the planet in real time." },
        { q: "Smart grids help by…", options: ["Wasting renewable energy", "Balancing supply and demand", "Disconnecting solar panels", "Lighting empty rooms"], answer: 1, why: "Balancing maximises clean-energy use." },
        { q: "Regulation-enforcement tech can detect…", options: ["Illegal dumping and emissions", "Lost socks", "Cricket scores", "Cake recipes"], answer: 0, why: "Sensors flag illegal activity." },
        { q: "Anti-poaching tech protects…", options: ["Wi-Fi routers", "Endangered species", "Phone batteries", "Smartwatches"], answer: 1, why: "Cameras and AI help save wildlife." },
        { q: "Which best describes the dual role of technology?", options: ["Only harmful", "Only helpful", "Causes problems and can solve them", "Has no effect"], answer: 2, why: "It is both a cause and a solution." },
        { q: "Smart lighting reduces use by…", options: ["Always being on", "Activating only when needed", "Using more bulbs", "Blocking sunlight"], answer: 1, why: "Sensors prevent waste." },
        { q: "True/False: drones can support anti-poaching efforts.", options: ["True", "False"], answer: 0, why: "Drones extend ranger visibility." },
        { q: "Which is NOT an example of positive impact?", options: ["Illegal e-waste dumping", "Smart grids", "Environmental sensors", "Traffic optimisation"], answer: 0, why: "Illegal dumping is harmful." },
      ],
    },
  ],
  flashcards: [
    { category: "MANUFACTURE", front: "Three key raw materials in devices", back: "Copper (non-renewable), palladium (non-renewable), arsenic (toxic)." },
    { category: "MANUFACTURE", front: "Why is mining harmful?", back: "Scars landscapes, destroys habitats, pollutes water and ecosystems." },
    { category: "MANUFACTURE", front: "Why are fossil fuels a manufacturing issue?", back: "Most factory energy comes from them, releasing CO₂ that drives climate change." },
    { category: "ENERGY", front: "% of lifetime energy in manufacture + disposal", back: "~70% — most of a device's energy footprint is outside actual use." },
    { category: "ENERGY", front: "% of lifetime energy during use", back: "~30% — including devices, networks and data centres." },
    { category: "ENERGY", front: "Why are data centres so energy-hungry?", back: "Run 24/7 to store and serve data, plus heavy cooling requirements." },
    { category: "DISPOSAL", front: "Annual global e-waste produced", back: "~50 million tonnes." },
    { category: "DISPOSAL", front: "% of e-waste recycled responsibly", back: "Only around 20%." },
    { category: "DISPOSAL", front: "Toxic chemicals leaking from e-waste", back: "Lead, mercury and cobalt — contaminate soil and groundwater." },
    { category: "WEEE", front: "WEEE stands for…", back: "Waste Electrical and Electronic Equipment regulations." },
    { category: "WEEE", front: "What does WEEE set?", back: "Legal recycling and collection targets to reduce e-waste harm." },
    { category: "RECYCLING", front: "Benefits of responsible recycling", back: "Recovers metals, reduces mining, prevents pollution, lowers fire risk, allows plastics reuse." },
    { category: "REPLACEMENT", front: "Average phone replacement cycle", back: "Around every 3 years (same for tablets, laptops, watches)." },
    { category: "REPLACEMENT", front: "Planned obsolescence", back: "Designing products with an intentionally limited useful life." },
    { category: "REPLACEMENT", front: "Manufacturer tactics that shorten device life", back: "Embedded batteries, glued/soldered parts, expensive spares, dropped software updates." },
    { category: "OWNERSHIP", front: "Responsible ownership actions", back: "Keep devices longer, buy second-hand, donate, recycle, reduce streaming, use efficiency settings." },
    { category: "REDUCE", front: "Top energy-saving settings", back: "Lower brightness, sleep mode, disable Bluetooth/Wi-Fi/GPS, close dormant apps, disconnect peripherals." },
    { category: "POSITIVE", front: "Positive technology uses", back: "Smart traffic, smart lighting, environmental monitoring, anti-poaching, smart grids." },
  ],
};
