import type { TopicContent } from "./types";

export const intellectualProperty: TopicContent = {
  slug: "intellectual-property",
  hero:
    "Intellectual property (IP) is the legal recognition that creative or intellectual work is a form of ownership. This module covers copyright, software licences, open source, plagiarism and DRM — the rules that decide who controls digital creations.",
  tags: ["COPYRIGHT", "LICENCES", "OPEN SOURCE", "PLAGIARISM", "DRM"],
  sections: [
    {
      id: "copyright",
      code: "01",
      title: "Copyright",
      explanation:
        "Copyright protects original works — text, music, art, software — automatically from the moment they are created. It gives the creator exclusive rights over how their work is used.",
      bullets: [
        "Applies to text, art, music, video, software and more.",
        "Automatic — no registration needed.",
        "Creator controls copying, distribution and adaptation.",
        "Lasts decades (usually creator's lifetime + 70 years).",
        "Using copyrighted work without permission is infringement.",
        "Exceptions are narrow (criticism, review, limited education use).",
        "Penalties: takedowns, fines, lawsuits.",
      ],
      paragraphs: [
        "Copying a song into your own video without permission is infringement, even if you do not make money from it. Free-use exceptions exist — for criticism, review or limited education — but they are narrow and frequently misunderstood.",
        "Platforms like YouTube enforce copyright at scale through automatic detection systems (e.g. Content ID), which fingerprint uploads against a database of protected works and issue takedowns or revenue claims.",
      ],
      quiz: [
        { q: "Copyright protection begins…", options: ["Only when you register the work", "Automatically the moment the work is created in fixed form", "Only after you pay a fee", "Only after publication"], answer: 1, why: "Automatic — no registration needed." },
        { q: "Which is NOT typically protected by copyright?", options: ["A song recording", "A piece of software", "A photograph", "An idea kept entirely in your head"], answer: 3, why: "Copyright protects expressions, not abstract ideas." },
        { q: "Standard copyright duration in the UK is approximately…", options: ["1 year", "10 years", "Creator's lifetime + 70 years", "Forever"], answer: 2, why: "Life + 70 years for most works." },
        { q: "A user uploads a clip of a copyrighted film to TikTok without permission. This is…", options: ["Always perfectly legal", "Likely copyright infringement", "Always a 'fair use' exception", "Encryption"], answer: 1, why: "Re-uploading protected work without permission infringes." },
        { q: "True/False: copyright is automatic and requires no registration.", options: ["True", "False"], answer: 0, why: "Granted on creation." },
        { q: "Which is a recognised exception to copyright?", options: ["Limited use for criticism, review or education", "Any personal use of any work", "All school projects forever", "Anything posted on TikTok"], answer: 0, why: "Narrow statutory exceptions." },
        { q: "Copyright gives the creator exclusive rights over…", options: ["Copying, distribution and adaptation of the work", "The right to tax other people", "The right to fly drones", "The right to pass new laws"], answer: 0, why: "Exclusive control over commercial exploitation." },
        { q: "Which scenario is copyright INFRINGEMENT?", options: ["Re-uploading someone's film to your channel without permission", "Quoting one short line with a clear citation in an essay", "Watching a film you bought legally", "Writing your own original song"], answer: 0, why: "Re-distribution without permission." },
        { q: "Platforms like YouTube enforce copyright at scale using…", options: ["Automatic detection systems (e.g. Content ID)", "Random manual fans", "Walkie-talkies", "Postal letters"], answer: 0, why: "Automated fingerprinting of uploads." },
        { q: "Consequences of copyright infringement can include…", options: ["Takedowns, fines and lawsuits", "Free streaming credits", "Faster Wi-Fi", "Better phone battery"], answer: 0, why: "Real civil and sometimes criminal penalties." },
      ],
    },
    {
      id: "licences",
      code: "02",
      title: "Software Licences",
      explanation:
        "Software licences set the legal terms under which software can be used, copied or modified. Different licences give very different rights and obligations.",
      bullets: [
        "Proprietary licence — use only, no changes allowed, source hidden.",
        "Freeware — free to use but source code is hidden.",
        "Shareware — free trial, pay to keep using.",
        "Open-source — source code available, often free to modify.",
        "Permissive licences (MIT, Apache) — almost no obligations.",
        "Copyleft licences (GPL) — derivatives must use the same licence.",
        "'Free to use' does NOT always mean 'free to copy and resell'.",
      ],
      paragraphs: [
        "Proprietary licences (Windows, Photoshop) restrict installs, ban redistribution and hide the source code. Freeware (e.g. some utilities) lets you run the software for free but doesn't open the source. Shareware lets you try, then forces payment to continue.",
        "Open source comes in two main flavours. Permissive licences (MIT) let you do almost anything — including using the code in proprietary, closed-source products. Copyleft licences (GPL) require that any modified versions you distribute must also be GPL — preserving openness down the chain.",
      ],
      quiz: [
        { q: "Proprietary software licences typically…", options: ["Hide source code and restrict copying / modification", "Are always free", "Force the user to share all changes", "Require government approval"], answer: 0, why: "Closed, restrictive — e.g. Windows, Photoshop." },
        { q: "Freeware is software that is…", options: ["Free to use but with hidden source code", "Always open source", "Always paid", "Always malware"], answer: 0, why: "Free of charge, closed source." },
        { q: "Shareware is software that…", options: ["Offers a free trial then requires payment to continue", "Is permanently free with full source", "Is always open source", "Is always adware"], answer: 0, why: "Trial-based commercial model." },
        { q: "Open-source software means…", options: ["The source code is available to read and (usually) modify", "It is always free of charge", "It is always copyleft", "It is always proprietary"], answer: 0, why: "Source openness varies in terms but is always accessible." },
        { q: "The GNU General Public Licence (GPL) is an example of a…", options: ["Copyleft licence — derivatives must use the same licence", "Permissive licence with no obligations", "Proprietary licence", "Freeware-only licence"], answer: 0, why: "Share-alike requirement." },
        { q: "The MIT licence is an example of a…", options: ["Permissive licence with almost no obligations", "Copyleft licence", "Closed-source licence", "Shareware licence"], answer: 0, why: "Minimal restrictions." },
        { q: "True/False: 'free to use' always means 'free to copy and resell'.", options: ["True", "False"], answer: 1, why: "Licences vary — freeware ≠ open source." },
        { q: "Why is it important to read a software licence before using code?", options: ["To know exactly what you can and cannot legally do with the software", "Because Wi-Fi requires it", "For entertainment only", "It unlocks free apps"], answer: 0, why: "Legal obligations vary widely." },
        { q: "Which is NOT a real software licence category?", options: ["Proprietary", "Freeware", "Shareware", "Sportsware"], answer: 3, why: "Sportsware is not a software licence." },
        { q: "If you modify code under a copyleft licence and distribute it, you must usually…", options: ["Release your modifications under the same copyleft licence", "Hide all source code", "Pay royalties to the original author", "Do nothing — there are no rules"], answer: 0, why: "Copyleft = share-alike." },
      ],
    },
    {
      id: "plagiarism-drm",
      code: "03",
      title: "Plagiarism & DRM",
      explanation:
        "Plagiarism is presenting someone else's work as your own. DRM (Digital Rights Management) is a technical system used to prevent unauthorised copying and use of digital media.",
      bullets: [
        "Plagiarism = copying without credit, even with paraphrasing.",
        "Consequences include failed work, expulsion, lost jobs and reputational damage.",
        "Citing sources is the cure for plagiarism.",
        "DRM = Digital Rights Management.",
        "DRM controls how digital media can be played, copied or shared.",
        "Examples: streaming services, copy-protected games, e-books.",
        "DRM controversy: it can block legitimate uses (e.g. personal backups).",
      ],
      paragraphs: [
        "Even AI-generated content needs careful sourcing to avoid passing off others' work as your own. Paraphrasing a paragraph from a website without citation is still plagiarism — the ideas and structure aren't yours.",
        "DRM protects creators from piracy but also restricts what paying customers can do — for example, stopping you backing up a Blu-ray you legally own, or moving an e-book to a different reader. Critics argue it limits user rights over content they paid for.",
      ],
      quiz: [
        { q: "Plagiarism is best defined as…", options: ["Presenting someone else's work or ideas as your own without credit", "Properly citing a source", "Paraphrasing with a clear citation", "Writing original work"], answer: 0, why: "Uncredited use of others' work." },
        { q: "The simplest way to AVOID plagiarism is to…", options: ["Always cite your sources clearly and accurately", "Copy faster", "Replace words with synonyms", "Delete the original source"], answer: 0, why: "Attribution is the cure." },
        { q: "DRM stands for…", options: ["Digital Rights Management", "Data Removal Method", "Disc Repair Mode", "Dynamic RAM"], answer: 0, why: "Standard expansion." },
        { q: "DRM is commonly used by…", options: ["Streaming services, video games and e-book platforms", "Postal workers", "Only one small website", "Cookies only"], answer: 0, why: "Anti-piracy technology across digital media." },
        { q: "What is a major downside of DRM for paying customers?", options: ["It can block legitimate uses such as personal backups or format-shifting", "It makes Wi-Fi faster", "It makes devices cheaper", "It produces free electricity"], answer: 0, why: "Restricts legal user activity." },
        { q: "Paraphrasing a paragraph from a website without citation is…", options: ["Still plagiarism — ideas and structure are not yours", "Always perfectly fine", "A new copyright law", "A form of encryption"], answer: 0, why: "Reworded but uncredited = plagiarism." },
        { q: "A school's typical penalty for plagiarism may include…", options: ["Loss of marks, failed coursework or possible expulsion", "Free Wi-Fi", "A medal", "A promotion"], answer: 0, why: "Serious academic penalties." },
        { q: "DRM's main aim is to prevent…", options: ["Unauthorised copying, sharing and distribution of digital media", "Server downtime", "Battery drain", "Software bugs"], answer: 0, why: "Protects creator revenue." },
        { q: "Which is NOT an example of DRM in use?", options: ["A physical safe-cracker tool", "Streaming services checking licences", "Copy-protected video games", "E-book reader restrictions"], answer: 0, why: "Self-evident — not DRM." },
        { q: "An ethical criticism of DRM is that it…", options: ["Restricts user freedom over content they have legally paid for", "Improves device battery", "Speeds up phones", "Reduces e-waste"], answer: 0, why: "Limits legitimate user rights." },
      ],
    },
  ],
  flashcards: [
    { category: "COPYRIGHT", front: "Copyright", back: "Automatic legal protection for original works — exclusive rights for ~creator's life + 70 years." },
    { category: "COPYRIGHT", front: "Copyright infringement", back: "Using protected work without permission — leads to takedowns, fines, lawsuits." },
    { category: "LICENCES", front: "Licence types", back: "Proprietary, freeware, shareware, open-source (permissive vs copyleft)." },
    { category: "LICENCES", front: "Copyleft vs permissive", back: "Copyleft (GPL) forces derivative works to share same licence; permissive (MIT) imposes almost no restrictions." },
    { category: "PLAGIARISM", front: "Plagiarism", back: "Presenting someone else's work as your own — avoided by clear citation." },
    { category: "DRM", front: "DRM", back: "Digital Rights Management — technical controls over how digital media can be played, copied or shared." },
    { category: "DRM", front: "DRM controversy", back: "Protects creators but can also block legitimate uses (backups, format-shifting)." },
  ],
};
