import type { TopicContent } from "./types";

export const legislation: TopicContent = {
  slug: "legislation",
  hero:
    "Three major UK laws set the rules of the digital world: the Data Protection Act 2018, the Computer Misuse Act 1990, and the Privacy and Electronic Communications Regulations 2003 (which cover cookies).",
  tags: ["DPA 2018", "CMA 1990", "PECR 2003", "PRINCIPLES", "RIGHTS", "OFFENCES", "COOKIES"],
  sections: [
    {
      id: "dpa-principles",
      code: "01",
      title: "DPA 2018 — Principles",
      explanation:
        "The Data Protection Act 2018 governs how organisations must handle personal data in the UK. It is built around seven core principles that every data controller must follow.",
      bullets: [
        "1. Lawfulness, fairness and transparency — process data legally and openly.",
        "2. Purpose limitation — only use data for the stated purpose.",
        "3. Data minimisation — collect only what is genuinely needed.",
        "4. Accuracy — keep data correct and up to date.",
        "5. Storage limitation — don't keep data longer than necessary.",
        "6. Security (integrity & confidentiality) — protect against loss, theft, unauthorised access.",
        "7. Accountability — organisations must prove they comply.",
      ],
      paragraphs: [
        "Lawfulness means there must be a legal basis (consent, contract, legal obligation, etc.) to process the data. Fairness means the use cannot harm the subject in unexpected ways. Transparency means the data subject is told what is being done.",
        "Data minimisation and storage limitation directly fight 'just-in-case' data hoarding. If a service doesn't truly need your phone number, it shouldn't collect it; if a record is no longer needed, it should be deleted.",
        "Accountability is the principle that ties everything together — controllers must keep records and be able to demonstrate compliance, not merely claim it. Breaches can lead to large fines from the Information Commissioner's Office (ICO).",
      ],
      quiz: [
        { q: "How many principles are at the core of the Data Protection Act 2018?", options: ["3", "5", "7", "12"], answer: 2, why: "Seven principles every controller must follow." },
        { q: "Which DPA principle requires organisations NOT to keep data longer than necessary?", options: ["Accuracy", "Storage limitation", "Lawfulness", "Accountability"], answer: 1, why: "Storage limitation forbids indefinite retention." },
        { q: "Which is NOT a DPA principle?", options: ["Data minimisation", "Purpose limitation", "Maximum collection of all available data", "Security"], answer: 2, why: "The DPA requires the OPPOSITE — minimisation." },
        { q: "The principle of accountability means an organisation must…", options: ["Be able to demonstrate compliance with the DPA", "Hide all records", "Outsource responsibility", "Refuse all audits"], answer: 0, why: "Show evidence — don't just claim it." },
        { q: "A retailer collects emails 'for delivery confirmation' then uses them for marketing. Which DPA principle is breached?", options: ["Accuracy", "Purpose limitation", "Storage limitation", "Security"], answer: 1, why: "Data must only be used for the stated purpose." },
        { q: "The 'accuracy' principle requires personal data to be…", options: ["Randomised", "Correct and kept up to date", "Encrypted at all times", "Made public"], answer: 1, why: "Errors must be corrected promptly." },
        { q: "'Lawfulness, fairness and transparency' means processing must be…", options: ["Legal, fair to the subject, and openly explained", "Hidden from the subject", "Always free of charge", "Carried out at random"], answer: 0, why: "Three-in-one foundational principle." },
        { q: "The security principle protects personal data against…", options: ["Loss, theft and unauthorised access", "Slow Wi-Fi", "Battery drain", "Sun damage"], answer: 0, why: "Integrity and confidentiality." },
        { q: "Which UK regulator can issue large fines for DPA breaches?", options: ["The Information Commissioner's Office (ICO)", "Ofcom only", "The Met Office", "The DVLA"], answer: 0, why: "ICO enforces DPA and PECR." },
        { q: "Data minimisation means organisations should collect…", options: ["Everything they possibly can", "Only the personal data genuinely needed for the purpose", "Random samples of users", "No data ever"], answer: 1, why: "Collect the minimum necessary." },
      ],
    },
    {
      id: "dpa-rights",
      code: "02",
      title: "DPA 2018 — Data Subject Rights",
      explanation:
        "The DPA gives data subjects (you and me) a clear set of rights over how organisations use our data. Knowing them is the most practical part of the law.",
      bullets: [
        "Right to be informed — know what is collected and why.",
        "Right of access — request a copy of your data (Subject Access Request).",
        "Right to correct inaccurate data — fix errors in your records.",
        "Right to erase — request deletion ('right to be forgotten').",
        "Right to object to processing — stop certain uses (e.g. marketing).",
        "Right to withdraw consent — at any time, as easily as it was given.",
        "Right to restrict processing — pause use while a dispute is resolved.",
        "Right to reuse / data portability — receive data in a portable format.",
        "Right to complain to the Information Commissioner (ICO).",
      ],
      paragraphs: [
        "Subject Access Requests (SARs) let you see exactly what an organisation holds on you, usually within one month and free of charge. This is one of the most powerful tools the law gives ordinary people.",
        "Withdrawing consent must be as easy as giving it — the law explicitly forbids hiding the unsubscribe option. Similarly, portability lets you move your data to a competitor, increasing user power against lock-in.",
      ],
      quiz: [
        { q: "Which right allows a user to request a free copy of all personal data an organisation holds about them?", options: ["Right of access (Subject Access Request)", "Right to read everyone's data", "Right to edit company accounts", "Right to enter the server room"], answer: 0, why: "SAR must usually be answered within one month." },
        { q: "The 'right to erasure' is also informally called…", options: ["Right to be forgotten", "Right to spam", "Right to encrypt", "Right to upload"], answer: 0, why: "Allows deletion requests under certain conditions." },
        { q: "Right to data portability lets a user…", options: ["Receive their data in a portable format and move it to another provider", "Print 100 paper copies", "Sell company data themselves", "Hide their identity"], answer: 0, why: "Reduces vendor lock-in." },
        { q: "If an organisation refuses to act, the user can complain to…", options: ["The Information Commissioner's Office (ICO)", "Their local football club", "Their ISP only", "The highway agency"], answer: 0, why: "ICO is the UK regulator." },
        { q: "The right to object lets a user…", options: ["Stop certain processing (e.g. direct marketing)", "Refuse all Wi-Fi", "Reject food deliveries", "Quit the country"], answer: 0, why: "Object to specific uses." },
        { q: "Under DPA, withdrawing consent must be…", options: ["As easy as giving consent originally was", "Impossible once given", "Charged at a fee", "Only allowed once per lifetime"], answer: 0, why: "Equally easy — no hidden unsubscribe links." },
        { q: "The right to restrict processing means use of data is…", options: ["Paused while a dispute or correction is resolved", "Banned forever", "Only paused on weekends", "Never paused"], answer: 0, why: "Temporary halt during disputes." },
        { q: "Right to rectification allows a user to…", options: ["Have inaccurate personal data corrected", "Edit others' records", "Delete the company", "Hack into databases"], answer: 0, why: "Fix factual errors." },
        { q: "True/False: under DPA you can object to your data being used for direct marketing.", options: ["True", "False"], answer: 0, why: "Explicit objection right." },
        { q: "The right to be informed requires organisations to tell users…", options: ["What data is being collected, why, and how it will be used", "Nothing at all", "Only their name", "Only after 10 years"], answer: 0, why: "Transparency to the data subject." },
      ],
    },
    {
      id: "cma",
      code: "03",
      title: "Computer Misuse Act 1990",
      explanation:
        "The CMA defines three computer-related criminal offences. It is the UK law that makes unauthorised access and damage to computer systems a crime.",
      bullets: [
        "Offence 1: Unauthorised access to a computer system.",
        "Offence 2: Unauthorised access with intent to commit a further crime.",
        "Offence 3: Unauthorised access to impair or damage systems (e.g. malware).",
        "Example O1: logging into a friend's account without permission.",
        "Example O2: gaining access to steal credit card details.",
        "Example O3: planting a virus or ransomware to damage systems.",
        "Intent is not required for Offence 1 — access alone is enough.",
      ],
      paragraphs: [
        "Logging into a friend's account 'as a joke' without permission is technically an offence under the CMA, even with no malicious intent. The unauthorised access itself is the crime.",
        "Offence 2 escalates the seriousness — using unauthorised access to commit fraud, theft, blackmail or similar. Offence 3 covers actively damaging systems, including releasing malware, ransomware, or wiping data.",
        "Penalties scale with offence: unauthorised access can mean up to 2 years, while malware that damages critical systems can carry sentences of 10+ years.",
      ],
      quiz: [
        { q: "How many main offences are defined by the Computer Misuse Act 1990?", options: ["2", "3", "5", "10"], answer: 1, why: "Three core offences." },
        { q: "Offence 1 of the CMA is…", options: ["Unauthorised access to a computer system", "Theft of physical property", "Speeding", "Sending spam"], answer: 0, why: "Basic offence — access alone is enough." },
        { q: "A student logs into their friend's school account 'as a joke' without permission. Which CMA offence applies?", options: ["Offence 1 — unauthorised access", "No offence — it was a joke", "Offence 3 — damaging systems", "Not covered by CMA"], answer: 0, why: "Intent isn't required — access alone is illegal." },
        { q: "An attacker breaks into a banking system to steal credit card numbers. Which CMA offence?", options: ["Offence 1 only", "Offence 2 — unauthorised access with intent to commit further crime", "Offence 3 only", "Not covered"], answer: 1, why: "Access PLUS intent to commit theft/fraud." },
        { q: "Planting ransomware that encrypts a company's files is…", options: ["Offence 1 only", "Offence 2 only", "Offence 3 — unauthorised modification to impair / damage systems", "Legal if you ask later"], answer: 2, why: "Damaging system integrity = Offence 3." },
        { q: "True/False: Offence 1 of the CMA requires the attacker to have malicious intent.", options: ["True", "False"], answer: 1, why: "Unauthorised access alone is enough." },
        { q: "A hacker uses a botnet to launch a DDoS that takes a website offline. The closest CMA offence is…", options: ["Offence 3 — impairing operation of a computer", "Offence 1 only", "Not covered by CMA", "Offence 2 only"], answer: 0, why: "DDoS impairs system availability." },
        { q: "In which year was the Computer Misuse Act passed?", options: ["1990", "1998", "2003", "2018"], answer: 0, why: "CMA 1990." },
        { q: "Which is NOT covered by the Computer Misuse Act?", options: ["Unauthorised access", "Theft of a physical bicycle", "Access with intent to commit further crime", "Damaging computer systems"], answer: 1, why: "Physical theft falls under Theft Act, not CMA." },
        { q: "The CMA primarily protects…", options: ["Computer systems and the integrity of data they hold", "Cars and bikes", "Library books", "Postal mail"], answer: 0, why: "Digital systems scope." },
      ],
    },
    {
      id: "cookies",
      code: "04",
      title: "Cookies & PECR 2003",
      explanation:
        "Cookies are small text files stored on a device by websites to recognise users and store preferences. Their use is regulated in the UK by the Privacy and Electronic Communications Regulations 2003.",
      bullets: [
        "A cookie = small text file stored on your device by a website.",
        "Cookies recognise returning users and store preferences.",
        "PECR 2003 = Privacy and Electronic Communications Regulations.",
        "Websites must inform users about cookies in use.",
        "Consent is required before non-essential cookies are set.",
        "Users may opt out of non-essential cookies at any time.",
        "Essential cookies (login session, shopping cart) do not require consent.",
        "Non-essential cookies (analytics, advertising) require explicit consent.",
      ],
      paragraphs: [
        "Cookies make modern websites usable — they remember you are logged in, keep items in your shopping cart and store language settings. Without them, every click would feel like visiting the site for the first time.",
        "The cookie banners you see on every website are the legal mechanism for informing users and getting consent under PECR. The DPA 2018 also applies because cookie data is usually personal data, so both laws work together.",
      ],
      quiz: [
        { q: "What is a cookie in web technology?", options: ["A type of virus", "A small text file stored on the user's device by a website", "A browser plugin", "An operating system"], answer: 1, why: "Small text file used to remember user state." },
        { q: "Which UK law regulates cookies?", options: ["Computer Misuse Act 1990", "Privacy and Electronic Communications Regulations 2003 (PECR)", "DPA 2018 alone", "WEEE Regulations"], answer: 1, why: "PECR 2003 sits alongside DPA for cookies." },
        { q: "Before setting non-essential cookies, a website must…", options: ["Get permission from Google", "Obtain explicit user consent", "Do nothing", "Pay a cookie licence fee"], answer: 1, why: "PECR explicitly requires consent." },
        { q: "Cookies typically store…", options: ["User preferences, login sessions and shopping basket contents", "User DNA samples", "Cake recipes", "Bluetooth signal strength"], answer: 0, why: "Preferences + session state." },
        { q: "Which is an ESSENTIAL cookie (no consent required)?", options: ["A login session or shopping cart cookie", "A third-party ad tracking cookie", "Spyware", "Adware"], answer: 0, why: "Required for the requested service to function." },
        { q: "Users have the right to…", options: ["Opt out of non-essential cookies at any time", "Never block any cookies", "Only block them on Tuesdays", "Block only on phones"], answer: 0, why: "PECR guarantees opt-out." },
        { q: "Cookie consent banners exist primarily because…", options: ["Of the legal duty to inform users and obtain consent under PECR + DPA", "They look decorative", "Of marketing trends", "Of free cookies promos"], answer: 0, why: "Compliance mechanism." },
        { q: "Cookies are stored on…", options: ["The user's own device (in the browser)", "Only the website server", "External satellites", "The keyboard"], answer: 0, why: "Client-side storage." },
        { q: "Which is NOT a typical purpose of cookies?", options: ["Remembering preferences", "Tracking analytics", "Booting the operating system", "Targeted advertising"], answer: 2, why: "Cookies cannot boot the OS." },
        { q: "In which year did the UK's main cookie regulation come into force?", options: ["1990", "2003 (PECR)", "2018", "1998"], answer: 1, why: "PECR 2003." },
      ],
    },
  ],
  flashcards: [
    { category: "DPA", front: "Seven DPA principles", back: "Lawfulness/fairness/transparency, purpose limitation, data minimisation, accuracy, storage limitation, security, accountability." },
    { category: "DPA", front: "Data subject rights", back: "Be informed, access, correct, erase, object, withdraw consent, restrict, reuse (portability), complain to ICO." },
    { category: "DPA", front: "ICO", back: "Information Commissioner's Office — UK regulator that enforces DPA and PECR." },
    { category: "CMA", front: "Three CMA offences", back: "Unauthorised access; access with intent for further crime; access to impair/damage systems." },
    { category: "CMA", front: "CMA examples", back: "Logging into another's account; stealing card details after access; planting malware." },
    { category: "COOKIES", front: "Cookie", back: "Small text file stored by a website on the user's device to recognise users and store preferences." },
    { category: "COOKIES", front: "PECR 2003", back: "UK cookie law: inform users, get consent for non-essential cookies, allow opt-out." },
    { category: "COOKIES", front: "Essential vs non-essential cookies", back: "Essential (login, basket) need no consent; non-essential (analytics, ads) require explicit consent." },
  ],
};
