import type { TopicContent } from "./types";

export const personalData: TopicContent = {
  slug: "personal-data",
  hero:
    "Every tap, payment, search and journey leaves data behind. This module covers your digital footprint, who collects your data, the benefits and risks of personalisation, and the ethical question of who actually owns it all.",
  tags: ["FOOTPRINT", "COLLECTORS", "BENEFITS", "DRAWBACKS", "OWNERSHIP", "DPA 2018"],
  sections: [
    {
      id: "footprint",
      code: "01",
      title: "Digital Footprint",
      explanation:
        "A digital footprint is the trail of data you leave behind whenever you use a digital service. Most of it is created without you doing anything special.",
      bullets: [
        "Websites visited, emails sent, social media activity.",
        "Card payments record what, where and when you bought.",
        "Google Maps logs every journey.",
        "Booking appointments leaves a record with healthcare and businesses.",
        "Mobile phones are tracked between cell masts continuously.",
      ],
      paragraphs: [
        "Your footprint has two parts: 'active' (things you post or send) and 'passive' (things collected silently in the background, like location pings).",
        "Even doing nothing on your phone, it is talking to cell masts, app servers and update services — generating data about where you are and what apps you have installed.",
      ],
      quiz: [
        { q: "A digital footprint is…", options: ["Your shoe size", "The data trail you leave from digital activity", "Your screen brightness", "A type of malware"], answer: 1, why: "Definition: trail of data left behind." },
        { q: "Which is an example of passive footprint data?", options: ["Posting on social media", "Cell mast tracking", "Writing an email", "Uploading a photo"], answer: 1, why: "Passive = collected without active user input." },
        { q: "Card payments record…", options: ["Only the amount", "What, where, when", "Nothing", "Only the date"], answer: 1, why: "Card data is detailed and timestamped." },
        { q: "Google Maps creates a footprint by…", options: ["Logging journeys and location", "Sending letters", "Changing your battery", "Encrypting Wi-Fi"], answer: 0, why: "Continuous location logging." },
        { q: "Phones generate location data via…", options: ["Cell masts and GPS", "Magic", "Your fingerprint only", "Bluetooth speakers"], answer: 0, why: "Cell tower handovers + GPS pings." },
        { q: "Which is NOT part of your footprint?", options: ["Browser history", "Calendar entries", "Heart rate from a smartwatch", "Air temperature in space"], answer: 3, why: "Unrelated to user activity." },
        { q: "Active footprint examples include…", options: ["Posting tweets", "Cell mast location", "Background app analytics", "Wi-Fi probe requests"], answer: 0, why: "Active = user-driven content." },
        { q: "True/False: deleting an account always removes all related data.", options: ["True", "False"], answer: 1, why: "Backups and shared copies often remain." },
        { q: "Booking a doctor's appointment online creates data for…", options: ["Only you", "The healthcare provider's records", "Nobody", "Only Google"], answer: 1, why: "Provider stores the booking and related health data." },
        { q: "Apps update in the background — this is…", options: ["Active footprint", "Passive footprint", "Not a footprint", "Antivirus"], answer: 1, why: "Background activity is passive." },
      ],
    },
    {
      id: "collectors",
      code: "02",
      title: "Who Collects Your Data",
      explanation:
        "Personal data is collected by many different third parties for many different reasons — some helpful, some commercial, some legal.",
      bullets: [
        "Advertisers — for targeting and profiling.",
        "Healthcare organisations — to manage care and research.",
        "Planners and councils — for transport, housing, services.",
        "Employers — for HR, security and monitoring.",
        "Law enforcement — to detect and investigate crime.",
        "Retailers — for purchase history and loyalty schemes.",
      ],
      paragraphs: [
        "Advertising networks are some of the largest collectors. They build detailed profiles to show you adverts that match your habits, interests and even mood.",
        "Police forces sometimes use mass data analysis to look for suspects. This can wrongly associate innocent people with crimes, raising serious civil-liberty concerns.",
      ],
      quiz: [
        { q: "Which group uses your data mainly for targeted adverts?", options: ["Advertisers", "Fire brigade", "Postal workers", "Plumbers"], answer: 0, why: "Advertisers build ad-targeting profiles." },
        { q: "Healthcare data is collected to…", options: ["Send spam", "Manage care and research", "Print maps", "Increase fuel prices"], answer: 1, why: "Used for treatment and population health." },
        { q: "Law enforcement uses personal data to…", options: ["Sell jewellery", "Detect and investigate crime", "Tune cars", "Manage farms"], answer: 1, why: "Investigative purposes." },
        { q: "A risk of police mass-data analysis is…", options: ["Faster Wi-Fi", "Wrongly associating innocent people with crimes", "Cheaper phones", "Cleaner data"], answer: 1, why: "False positives harm individuals." },
        { q: "Loyalty cards help retailers…", options: ["Track purchase history", "Wash floors", "Repair phones", "Build websites only"], answer: 0, why: "Loyalty schemes log purchases." },
        { q: "Employers may monitor staff for…", options: ["Security and performance", "Only fun", "Cooking only", "Game design"], answer: 0, why: "HR and security reasons." },
        { q: "Council planners use personal data for…", options: ["Targeting ads", "Transport and service planning", "Hacking", "Filming TV shows"], answer: 1, why: "Planning needs aggregate behaviour data." },
        { q: "Which is NOT a typical collector?", options: ["Advertisers", "Retailers", "Healthcare", "The Moon"], answer: 3, why: "Self-evident — Moon is not a collector." },
        { q: "True/False: data collection by many parties is normal today.", options: ["True", "False"], answer: 0, why: "It is widespread across modern services." },
        { q: "Why is profiling controversial?", options: ["It is illegal everywhere", "It can be invasive and discriminatory", "It improves Wi-Fi", "It removes ads"], answer: 1, why: "Risks of intrusion and discrimination." },
      ],
    },
    {
      id: "benefits-drawbacks",
      code: "03",
      title: "Benefits & Drawbacks",
      explanation:
        "Collecting personal data has real upsides — but also serious risks. Both sides of the trade-off must be understood.",
      bullets: [
        "Benefits: personalisation, convenience, better services.",
        "Drawbacks: privacy concerns, unclear collection, hidden sharing.",
        "Security risks if data is leaked or stolen.",
        "Discrimination risk if profiles are biased.",
        "Civil-liberties concerns from mass surveillance.",
        "Police data analysis can wrongly associate innocent people with crimes.",
      ],
      paragraphs: [
        "Personalisation means recommendations, autofill, faster checkout and tailored news. Convenience is real — but it has a hidden price.",
        "When you don't know who has your data or who they share it with, you cannot meaningfully consent. Leaks then expose information you never intended to share.",
        "Profiling can quietly discriminate — denying loans, jobs or insurance based on patterns inferred from your data, sometimes without the company even realising it.",
      ],
      quiz: [
        { q: "A clear benefit of personal data collection is…", options: ["Personalisation", "Random shutdowns", "Bigger landfills", "Slower service"], answer: 0, why: "Personalised recommendations and convenience." },
        { q: "A drawback is…", options: ["Privacy concerns", "Better customer support", "Faster downloads", "Free Wi-Fi"], answer: 0, why: "Privacy is a major risk." },
        { q: "If data is leaked, the main risk is…", options: ["Security breach exposing private info", "Fewer adverts", "Slower phone charging", "Brighter screens"], answer: 0, why: "Breaches reveal sensitive data." },
        { q: "Discrimination risk comes from…", options: ["Biased profiles", "Better Wi-Fi", "More holidays", "Less data"], answer: 0, why: "Biased data → biased decisions." },
        { q: "'Civil liberties' refers to…", options: ["Internet speed", "Personal rights and freedoms", "Phone colours", "Battery health"], answer: 1, why: "Fundamental rights of individuals." },
        { q: "Police data analysis can wrongly…", options: ["Speed up Wi-Fi", "Associate innocent people with crimes", "Repair cars", "Plant trees"], answer: 1, why: "False positives cause real harm." },
        { q: "Which is NOT a benefit?", options: ["Convenience", "Personalisation", "Unauthorised sharing", "Better recommendations"], answer: 2, why: "Sharing without consent is a drawback." },
        { q: "Unclear collection means…", options: ["Users know exactly what's collected", "Users don't know what's collected or why", "No data is collected", "Data is encrypted"], answer: 1, why: "Lack of transparency = unclear collection." },
        { q: "True/False: personalisation always justifies any data collection.", options: ["True", "False"], answer: 1, why: "Consent, scope and risk also matter." },
        { q: "A leaked database can lead to…", options: ["Identity theft", "Faster delivery", "Free upgrades", "Better service"], answer: 0, why: "Stolen data is misused." },
      ],
    },
    {
      id: "ownership",
      code: "04",
      title: "Owning the Data",
      explanation:
        "Who actually owns your data? Sometimes it's you — sometimes it isn't. Different organisations claim different rights and the law tries to set boundaries.",
      bullets: [
        "Social media platforms often have licences over uploaded images.",
        "NHS holds patient medical records (with strict rules).",
        "Websites record visitor activity data.",
        "Retailers can sell purchase history to other companies.",
        "Search engines collect and analyse search history.",
        "The Data Protection Act 2018 sets strict rules on use.",
      ],
      paragraphs: [
        "Reading platform terms of service usually reveals broad licences that let the company use your uploaded content for many purposes — but you still own the original work.",
        "Health records have stronger protections than commercial data. Misusing them carries large fines because of the sensitivity of the information.",
        "Even your search history is data. Search engines analyse it to improve results and to build advertising profiles, often across many services.",
      ],
      quiz: [
        { q: "Who usually owns your medical records?", options: ["Random advertiser", "Healthcare provider (e.g. NHS), under strict rules", "Your friends", "The data is freely public"], answer: 1, why: "Provider holds and protects under law." },
        { q: "Social media platforms typically…", options: ["Own all your photos", "Take a licence to use uploaded images", "Print your photos", "Email them to everyone"], answer: 1, why: "Licence, not full ownership." },
        { q: "Retailers may legally…", options: ["Sell purchase history to other companies", "Read your texts", "Read your DMs", "Track your location 24/7"], answer: 0, why: "Common practice with consent." },
        { q: "Search engines collect…", options: ["Search history", "Only the colour of your phone", "Your fingerprints", "Your voice 24/7"], answer: 0, why: "Search history is recorded and analysed." },
        { q: "Which law sets strict rules on data use in the UK?", options: ["Data Protection Act 2018", "Highway Code", "Computer Repair Act", "Wi-Fi Act"], answer: 0, why: "DPA 2018 is the key legislation." },
        { q: "True/False: you fully control all your data online.", options: ["True", "False"], answer: 1, why: "In practice, control is limited." },
        { q: "Strong protections apply to…", options: ["Medical records", "Cat photos", "Public memes", "Stock images"], answer: 0, why: "Health data is highly sensitive." },
        { q: "Your purchase history is most useful to…", options: ["Advertisers and retailers", "Random strangers", "The weather service", "Banks only"], answer: 0, why: "Used to target offers." },
        { q: "Ethical issue with retailer data selling…", options: ["You may not know who ends up with it", "It is fully transparent", "It is illegal everywhere", "Nothing"], answer: 0, why: "Lack of clarity is a key issue." },
        { q: "Which is most likely to be 'owned' by the user originally?", options: ["A photo they took", "A government census record", "A hospital database", "An ISP log"], answer: 0, why: "User created the work." },
      ],
    },
  ],
  flashcards: [
    { category: "FOOTPRINT", front: "Digital footprint", back: "Trail of data left by using digital services — active (posts) and passive (logs)." },
    { category: "FOOTPRINT", front: "How phones generate location data", back: "Via GPS and cell-mast handovers." },
    { category: "COLLECTORS", front: "Six common data collectors", back: "Advertisers, healthcare, planners, employers, law enforcement, retailers." },
    { category: "BENEFITS", front: "Two clear benefits of personal data", back: "Personalisation and convenience." },
    { category: "DRAWBACKS", front: "Five key drawbacks", back: "Privacy concerns, unclear collection, sharing, security risk, discrimination/civil-liberty risks." },
    { category: "OWNERSHIP", front: "Who owns uploaded social media photos?", back: "You own them, but platforms take broad licences to use them." },
    { category: "OWNERSHIP", front: "Who holds NHS medical records?", back: "Healthcare provider — under strict legal protections." },
    { category: "LAW", front: "UK law setting strict rules on data use", back: "Data Protection Act 2018." },
  ],
};
