import type { TopicContent } from "./types";

export const protectingSystems: TopicContent = {
  slug: "protecting-systems",
  hero:
    "Defending digital systems means layering physical, technical and human controls: firewalls, encryption, access control, anti-malware, backups, AUPs and user education. This module covers the full stack.",
  tags: ["FIREWALL", "ENCRYPTION", "ACCESS", "ANTI-MALWARE", "BACKUPS", "AUP"],
  sections: [
    {
      id: "firewalls",
      code: "01",
      title: "Firewalls",
      explanation:
        "A firewall controls network traffic between a trusted network and an untrusted one (usually the internet). It filters traffic against a set of rules and blocks suspicious activity.",
      bullets: [
        "Filters incoming and outgoing traffic.",
        "Hardware or software based.",
        "Uses rule sets and packet inspection.",
        "Can perform stateful inspection (tracks active connections).",
        "Often combined with intrusion-detection systems (IDS/IPS).",
      ],
      paragraphs: [
        "Firewalls block traffic that doesn't match an allowed pattern. They can stop attacks before they reach internal systems and can also stop infected machines from contacting attackers outside.",
        "Modern next-generation firewalls (NGFWs) also look at the application layer, identifying which application is using a connection and blocking suspicious patterns.",
      ],
      quiz: [
        { q: "A firewall sits between…", options: ["A trusted and untrusted network", "Your screen and your eyes", "Two CPUs", "Two batteries"], answer: 0, why: "Boundary control point." },
        { q: "Firewalls can be…", options: ["Hardware or software", "Only paper", "Only USB", "Only printers"], answer: 0, why: "Both forms exist." },
        { q: "Stateful inspection means…", options: ["Tracking active connections", "Random blocking", "Ignoring traffic", "Encrypting Wi-Fi"], answer: 0, why: "Context-aware filtering." },
        { q: "IDS stands for…", options: ["Intrusion Detection System", "Internet Display Sync", "Internal Device Setup", "Image Disk Suite"], answer: 0, why: "Defence layer." },
        { q: "Modern firewalls can identify…", options: ["Which application is using a connection", "Cat photos only", "Sentence grammar", "Battery health"], answer: 0, why: "Application-layer inspection." },
        { q: "True/False: firewalls can stop infected machines from contacting attackers.", options: ["True", "False"], answer: 0, why: "Outbound filtering." },
        { q: "Rule sets define…", options: ["What traffic is allowed or blocked", "Wi-Fi colours", "Phone brightness", "OS theme"], answer: 0, why: "Policies." },
        { q: "Firewalls are usually placed…", options: ["At the network perimeter and key choke points", "Inside the keyboard", "On the desk only", "On the cloud icon"], answer: 0, why: "Boundary positioning." },
        { q: "Firewall + IDS together provide…", options: ["Defence in depth", "Slower internet only", "No benefit", "Free phones"], answer: 0, why: "Layered security." },
        { q: "A firewall alone is…", options: ["Necessary but not sufficient", "Total security", "Useless", "A backup"], answer: 0, why: "Part of a defence stack." },
      ],
    },
    {
      id: "encryption",
      code: "02",
      title: "Encryption",
      explanation:
        "Encryption scrambles data using an algorithm and a key, so only people with the correct key can read it. It protects data both at rest (stored) and in transit (on the network).",
      bullets: [
        "Symmetric encryption — same key for encrypt and decrypt.",
        "Asymmetric encryption — public + private key pair.",
        "Common algorithms: AES (symmetric), RSA (asymmetric).",
        "HTTPS = TLS encryption over the web.",
        "Encryption at rest protects stored files.",
        "Encryption in transit protects data while it moves.",
      ],
      paragraphs: [
        "Asymmetric encryption underpins modern web security: your browser uses the website's public key to set up a secure session, and only the website's private key can complete it.",
        "Even if attackers steal an encrypted database, they cannot read it without the key — so strong encryption can turn a breach into a non-event.",
      ],
      quiz: [
        { q: "Symmetric encryption uses…", options: ["The same key to encrypt and decrypt", "Two different keys", "No key", "A hash only"], answer: 0, why: "Shared key model." },
        { q: "Asymmetric encryption uses…", options: ["Public + private key pair", "Same key for both", "Three identical keys", "No keys"], answer: 0, why: "Key pair model." },
        { q: "AES is…", options: ["A symmetric algorithm", "An asymmetric algorithm", "A worm", "A type of cable"], answer: 0, why: "Modern symmetric standard." },
        { q: "RSA is…", options: ["Asymmetric encryption", "Symmetric encryption", "A virus", "An OS"], answer: 0, why: "Classic asymmetric." },
        { q: "HTTPS uses…", options: ["TLS encryption", "FTP", "SMTP only", "Plain text"], answer: 0, why: "Encrypted HTTP via TLS." },
        { q: "Encryption at rest protects…", options: ["Stored data on disk", "Only in-flight data", "Only sound", "Only screen content"], answer: 0, why: "Files / databases on disk." },
        { q: "Encryption in transit protects data…", options: ["While it is being sent across a network", "When deleted", "When printed", "When backed up to tape only"], answer: 0, why: "TLS / VPN protect transit." },
        { q: "True/False: encrypted data is unreadable without the key.", options: ["True", "False"], answer: 0, why: "Strong encryption is effectively unbreakable without it." },
        { q: "Why encrypt databases?", options: ["So a breach doesn't expose readable data", "To slow down apps", "To run cooler", "To save power"], answer: 0, why: "Reduces breach impact." },
        { q: "A 'public key' is…", options: ["Safe to share — used to encrypt to its owner", "Always secret", "Used only for symmetric crypto", "Never used"], answer: 0, why: "Pair with private key." },
      ],
    },
    {
      id: "access",
      code: "03",
      title: "Access Control & Authentication",
      explanation:
        "Access control decides who can do what. Authentication proves identity, authorisation decides which actions are allowed, and auditing tracks what happened.",
      bullets: [
        "Strong passwords — long, mixed character types.",
        "Two-factor authentication (2FA) — something you know + something you have/are.",
        "Biometrics — fingerprint, face, iris.",
        "Role-based access control (RBAC).",
        "Principle of least privilege.",
        "Account lockouts after failed attempts.",
      ],
      paragraphs: [
        "2FA makes a stolen password almost useless. Even if attackers know it, they still need your phone or hardware token.",
        "RBAC assigns permissions based on job role. A teacher account doesn't need server-admin rights — give it just what it needs and no more.",
      ],
      quiz: [
        { q: "2FA combines…", options: ["Two different factors (know / have / are)", "Two passwords", "Two phones only", "Two emails"], answer: 0, why: "Multi-factor model." },
        { q: "Biometrics include…", options: ["Fingerprint, face, iris", "Only passwords", "Only PINs", "Only USB keys"], answer: 0, why: "Body-based factors." },
        { q: "Least privilege means…", options: ["Minimum access required", "Maximum access for everyone", "No access ever", "Random access"], answer: 0, why: "Defensive principle." },
        { q: "RBAC = …", options: ["Role-Based Access Control", "Random Backup And Cache", "Routine Bus Audit Channel", "Read Block Audit Cycle"], answer: 0, why: "Permissions by role." },
        { q: "A strong password is…", options: ["Long with mixed characters", "Your pet's name", "1234", "Same as username"], answer: 0, why: "Entropy matters." },
        { q: "Why lock accounts after several failed logins?", options: ["Slows brute force", "Saves energy", "Cleans memory", "Updates apps"], answer: 0, why: "Throttles attackers." },
        { q: "Authentication vs authorisation…", options: ["Auth = who; Authz = what they can do", "Same thing", "Both are about Wi-Fi", "Neither matters"], answer: 0, why: "Distinct concepts." },
        { q: "Auditing records…", options: ["What actions were taken", "Cookies recipes", "Wi-Fi colours", "Background apps"], answer: 0, why: "Logs for review." },
        { q: "True/False: 2FA makes stolen passwords almost useless alone.", options: ["True", "False"], answer: 0, why: "Need second factor too." },
        { q: "Biometric weakness…", options: ["Can't be changed if compromised", "Always plain text", "Always fail", "Always open"], answer: 0, why: "You can't reset your face." },
      ],
    },
    {
      id: "anti-malware",
      code: "04",
      title: "Anti-Malware & Heuristics",
      explanation:
        "Anti-malware scans for and removes malicious software. It uses signature databases for known threats and heuristic analysis for unknown ones.",
      bullets: [
        "Signature detection — matches against known malware fingerprints.",
        "Heuristic analysis — flags suspicious behaviour patterns.",
        "Real-time scanning — checks files as they are opened.",
        "Sandboxing — runs suspicious code in isolation.",
        "Regular updates are essential.",
      ],
      paragraphs: [
        "Signatures catch known malware quickly but can't see brand-new threats. Heuristics fill that gap by spotting behaviour typical of malware, even from samples never seen before.",
        "Sandboxing isolates suspect code so it can't touch the real system. If it tries something malicious in the sandbox, it gets blocked before it can do harm in production.",
      ],
      quiz: [
        { q: "Signature detection works by…", options: ["Matching known malware fingerprints", "Reading minds", "Random scans", "Encrypting Wi-Fi"], answer: 0, why: "Definition." },
        { q: "Heuristic analysis flags…", options: ["Suspicious behaviour, even from unknown code", "Only known viruses", "Random apps", "All photos"], answer: 0, why: "Behaviour-based." },
        { q: "Sandboxing runs code…", options: ["In an isolated environment", "On bare metal", "In the BIOS only", "Inside the screen"], answer: 0, why: "Isolation for safety." },
        { q: "Why update anti-malware often?", options: ["New threats appear constantly", "It is fun", "It refreshes RAM", "It changes Wi-Fi colour"], answer: 0, why: "Signatures must be current." },
        { q: "Real-time scanning…", options: ["Checks files as they're opened", "Runs once a year", "Only checks USB drives", "Only photos"], answer: 0, why: "Continuous protection." },
        { q: "Heuristics help against…", options: ["Zero-day / unknown malware", "Only old viruses", "Spam emails only", "Wi-Fi noise"], answer: 0, why: "Behaviour catches the unknown." },
        { q: "True/False: signature databases catch all malware.", options: ["True", "False"], answer: 1, why: "They miss brand-new threats." },
        { q: "Sandboxing prevents…", options: ["Real system damage from suspicious code", "Wi-Fi disconnects", "Screen burn-in", "Slow boots"], answer: 0, why: "Containment." },
        { q: "Which is NOT an anti-malware technique?", options: ["Signature", "Heuristic", "Sandbox", "DDoS"], answer: 3, why: "DDoS is an attack." },
        { q: "Best practice for protection…", options: ["Combine signature + heuristic + updates + user training", "Only one method", "Nothing", "Disable updates"], answer: 0, why: "Layered defence." },
      ],
    },
    {
      id: "backups",
      code: "05",
      title: "Backups & RAID",
      explanation:
        "Backups protect against data loss from failure, attack or human error. RAID arrays add redundancy at the disk level so a single drive failure does not lose data.",
      bullets: [
        "Full backup — copies everything.",
        "Incremental backup — copies only what changed since last backup.",
        "Differential backup — copies changes since last FULL backup.",
        "3-2-1 rule: 3 copies, 2 media types, 1 offsite.",
        "RAID 0 — striping (no redundancy).",
        "RAID 1 — mirroring (full duplicate).",
        "RAID 5 — striping with parity (survives 1 disk failure).",
        "RAID 10 — mirroring + striping.",
      ],
      paragraphs: [
        "Incremental backups are fast and small but slower to restore. Full backups are large but fastest to restore. Most organisations combine both.",
        "RAID is not a backup. If ransomware encrypts your files, every copy in the RAID is encrypted too. Real backups must be separated from the live system.",
      ],
      quiz: [
        { q: "Full backup copies…", options: ["Everything", "Only new files", "Only deleted files", "Nothing"], answer: 0, why: "Complete snapshot." },
        { q: "Incremental backup copies…", options: ["Only changes since last backup", "Everything every time", "Only photos", "Only Wi-Fi data"], answer: 0, why: "Delta-based." },
        { q: "Differential backup copies…", options: ["Changes since last FULL backup", "Only one file", "Everything", "Nothing"], answer: 0, why: "Larger than incremental, faster to restore." },
        { q: "3-2-1 rule means…", options: ["3 copies, 2 media types, 1 offsite", "3 days, 2 sites, 1 person", "Random numbers", "Only 3 files"], answer: 0, why: "Standard rule of thumb." },
        { q: "RAID 0 provides…", options: ["Striping but no redundancy", "Mirroring", "Encryption", "Backup"], answer: 0, why: "Performance only." },
        { q: "RAID 1 provides…", options: ["Mirroring", "Striping only", "Encryption", "Anti-malware"], answer: 0, why: "Full duplicate." },
        { q: "RAID 5 can survive…", options: ["One disk failure", "Two disk failures", "Three failures", "Zero"], answer: 0, why: "Parity-based." },
        { q: "True/False: RAID counts as a backup.", options: ["True", "False"], answer: 1, why: "RAID protects against disk failure, not ransomware/deletion." },
        { q: "Offsite backups protect against…", options: ["Fire, theft, ransomware on the local network", "Wi-Fi outages only", "Phone weight", "Battery age"], answer: 0, why: "Geographic separation." },
        { q: "Combining full + incremental…", options: ["Balances size and restore speed", "Doubles risk", "Removes data", "Has no benefit"], answer: 0, why: "Common best practice." },
      ],
    },
    {
      id: "aup",
      code: "06",
      title: "Acceptable Use Policies (AUP)",
      explanation:
        "An Acceptable Use Policy sets out the rules that staff, students or users must follow when using an organisation's digital systems. It also defines consequences for breaking them.",
      bullets: [
        "Defines acceptable behaviour on company systems.",
        "Covers passwords, sharing, personal use, downloads, social media.",
        "Specifies banned activities (e.g. piracy, harassment).",
        "Outlines monitoring and consequences for breaches.",
        "Should be signed and regularly reviewed.",
      ],
      paragraphs: [
        "A clear AUP makes expectations explicit. Users can't say 'I didn't know I couldn't do that' if the policy is signed and visible.",
        "Combined with user education, AUPs reduce risky behaviour and provide legal backing if disciplinary action is needed.",
      ],
      quiz: [
        { q: "AUP stands for…", options: ["Acceptable Use Policy", "Account Update Process", "Automated User Patch", "Approved Upload Path"], answer: 0, why: "Definition." },
        { q: "AUPs usually cover…", options: ["Passwords, sharing, downloads, social media", "Cooking recipes", "Travel plans", "Sports scores"], answer: 0, why: "Use of company systems." },
        { q: "Breaching an AUP can lead to…", options: ["Disciplinary action or dismissal", "A free phone", "Faster Wi-Fi", "Promotion"], answer: 0, why: "Consequences are defined." },
        { q: "Why have users sign an AUP?", options: ["Proves they know the rules", "It's decorative", "Required by Wi-Fi", "Random tradition"], answer: 0, why: "Establishes accountability." },
        { q: "AUPs should be…", options: ["Reviewed and updated regularly", "Written once and forgotten", "Hidden from users", "Only verbal"], answer: 0, why: "Tech and threats evolve." },
        { q: "True/False: an AUP alone secures a company.", options: ["True", "False"], answer: 1, why: "Needs technical controls + training too." },
        { q: "AUPs typically ban…", options: ["Piracy and harassment", "Sending email", "Using laptops", "Logging in"], answer: 0, why: "Common forbidden activities." },
        { q: "AUPs help with…", options: ["Setting clear expectations and legal backing", "Cooling servers", "Improving Wi-Fi", "Charging batteries"], answer: 0, why: "Policy + legal value." },
        { q: "Which is NOT typically in an AUP?", options: ["Password requirements", "Acceptable software list", "Monitoring statement", "Lunch menu"], answer: 3, why: "Self-evident." },
        { q: "AUP + user education =", options: ["Stronger human security layer", "Slower Wi-Fi", "Free upgrades", "Faster boot"], answer: 0, why: "Combined effect." },
      ],
    },
  ],
  flashcards: [
    { category: "FIREWALL", front: "Firewall purpose", back: "Filters traffic between trusted and untrusted networks using rule sets; can be hardware or software." },
    { category: "FIREWALL", front: "Stateful inspection", back: "Tracks active connections to make smarter allow/block decisions." },
    { category: "ENCRYPTION", front: "Symmetric vs Asymmetric", back: "Same key for both vs public+private key pair (AES vs RSA)." },
    { category: "ENCRYPTION", front: "At rest vs in transit", back: "Protects stored data on disk vs protects data while moving across networks (HTTPS/TLS, VPN)." },
    { category: "ACCESS", front: "2FA", back: "Two different factors from: something you know, something you have, something you are." },
    { category: "ACCESS", front: "Least privilege", back: "Give each user/process the minimum access needed to do its job." },
    { category: "ANTI-MALWARE", front: "Signature vs Heuristic", back: "Known fingerprints vs suspicious-behaviour patterns; heuristics catch unknown malware." },
    { category: "ANTI-MALWARE", front: "Sandboxing", back: "Run suspect code in isolation to safely observe what it does before allowing it to run live." },
    { category: "BACKUPS", front: "Full / Incremental / Differential", back: "All / changes since last backup / changes since last FULL backup." },
    { category: "BACKUPS", front: "3-2-1 rule", back: "3 copies of data, 2 different media types, 1 stored offsite." },
    { category: "BACKUPS", front: "RAID levels", back: "0 = striping; 1 = mirroring; 5 = striping with parity (survives one disk loss); 10 = mirror + stripe." },
    { category: "BACKUPS", front: "Is RAID a backup?", back: "No — RAID protects against disk failure, not against ransomware, deletion or fire." },
    { category: "AUP", front: "AUP", back: "Acceptable Use Policy — rules for using an organisation's digital systems plus consequences for breaches." },
  ],
};
