import type { TopicContent } from "./types";

export const protectingSystems: TopicContent = {
  slug: "protecting-systems",
  hero:
    "Every threat has a counter-measure. This module covers the layered defences that keep modern systems safe — authentication, encryption, firewalls, antivirus, backups, RAID and the human policies that hold it all together.",
  tags: ["AUTH", "ENCRYPTION", "FIREWALL", "ANTIVIRUS", "BACKUPS", "RAID", "AUP"],
  sections: [
    {
      id: "auth",
      code: "01",
      title: "Authentication & Access Control",
      explanation:
        "Authentication proves who a user is. Access control then decides what they are allowed to do. Together they form the front door of every secure system.",
      bullets: [
        "Strong passwords: long, mixed characters, not reused.",
        "Multi-factor authentication (MFA): something you know + have + are.",
        "Biometric authentication: fingerprint, face, iris, voice.",
        "Two-step verification: password + one-time code by SMS or app.",
        "Account lockout after repeated failures defeats brute force.",
        "Principle of least privilege: users get the minimum access needed.",
        "Role-based access control (RBAC): permissions assigned by role.",
      ],
      paragraphs: [
        "A strong password (12+ characters, mixed types) takes practically forever to brute force, but it is useless if reused on another site that is breached — credential stuffing relies on this. MFA solves the problem by requiring a second factor.",
        "Biometrics are convenient (no password to remember) but cannot be 'changed' if leaked — a stolen fingerprint scan is yours forever. Least privilege limits the damage if an account is compromised: a junior account stolen cannot grant admin powers.",
      ],
      quiz: [
        { q: "Multi-factor authentication combines something you know with something you…", options: ["Have AND something you are", "Say AND do", "Buy AND sell", "Watch AND read"], answer: 0, why: "Three categories — knowledge, possession, biometric." },
        { q: "Which is an example of biometric authentication?", options: ["A fingerprint scan", "A password", "A username", "An email address"], answer: 0, why: "Physical trait used as identity." },
        { q: "The principle of least privilege means…", options: ["Users are given only the minimum access rights needed for their role", "Every user is given full administrator rights", "No user has any access", "Access rights are random"], answer: 0, why: "Limits blast radius of compromised accounts." },
        { q: "Account lockout after a number of failed logins mainly defeats…", options: ["Brute-force password attacks", "Cold weather", "Rain", "Wi-Fi outages"], answer: 0, why: "Stops repeated guessing." },
        { q: "Which is a strong password?", options: ["A long, mixed-character, unique passphrase not reused elsewhere", "Just your first name", "Password123", "Repeated letters like aaaaaa"], answer: 0, why: "Length + complexity + uniqueness." },
        { q: "Two-step verification adds security by requiring…", options: ["A second factor such as a one-time code from an app or SMS", "More adverts", "Bigger fonts", "More RAM"], answer: 0, why: "Defeats stolen-password attacks." },
        { q: "RBAC stands for…", options: ["Role-Based Access Control", "Random Byte Access Channel", "RAM-Based Audio Control", "Reverse Boot Access Cycle"], answer: 0, why: "Permissions assigned by role, not per-user." },
        { q: "A KEY disadvantage of biometric authentication is that…", options: ["If a biometric is leaked, it cannot simply be 'changed' like a password", "It always works perfectly", "It is free of hardware cost", "It boosts Wi-Fi"], answer: 0, why: "Biometrics are permanent — leak is forever." },
        { q: "MFA is particularly effective against…", options: ["Credential stuffing and simple phishing attacks that capture only a password", "Lightning", "Heat damage", "Rain"], answer: 0, why: "A leaked password alone is no longer enough." },
        { q: "BEST practice for personal account security combines…", options: ["Strong unique passwords + MFA + least privilege + a password manager", "The same password on every site", "No passwords at all", "Sticky notes on the monitor"], answer: 0, why: "Layered defence." },
      ],
    },
    {
      id: "encryption",
      code: "02",
      title: "Encryption",
      explanation:
        "Encryption scrambles data so only authorised people with the right key can read it. It protects data both 'at rest' (on disk) and 'in transit' (over networks).",
      bullets: [
        "Plaintext = readable data; ciphertext = encrypted data.",
        "Symmetric encryption: same key encrypts and decrypts (fast, e.g. AES).",
        "Asymmetric encryption: public + private key pair (e.g. RSA).",
        "Public key encrypts; only matching private key can decrypt.",
        "HTTPS uses encryption (TLS) to protect web traffic.",
        "Encryption at rest protects stored data (disk, database).",
        "Encryption in transit protects data moving across networks.",
        "Strong encryption is useless if keys are leaked or weak.",
      ],
      paragraphs: [
        "Symmetric encryption is fast and used for bulk data (your hard drive, your phone storage). The challenge is sharing the secret key safely. Asymmetric encryption solves the key-sharing problem with public/private key pairs.",
        "HTTPS combines both: asymmetric encryption sets up the secure channel, then symmetric encryption protects the actual traffic. The padlock icon in a browser indicates this TLS-secured connection.",
      ],
      quiz: [
        { q: "When data is encrypted, plaintext becomes…", options: ["Ciphertext — scrambled and unreadable without the correct key", "Audio data", "Image data", "Binary data only"], answer: 0, why: "Definition of encryption output." },
        { q: "Symmetric encryption uses…", options: ["The SAME key to encrypt and decrypt (fast — e.g. AES)", "Two different keys", "No keys at all", "A different key every minute"], answer: 0, why: "One shared secret key." },
        { q: "Asymmetric encryption uses…", options: ["A public + private key pair (e.g. RSA)", "Only one key", "No keys at all", "Only Wi-Fi credentials"], answer: 0, why: "Solves the key-sharing problem." },
        { q: "Which security technology protects web traffic in HTTPS?", options: ["Encryption via TLS", "Plaintext only", "FTP", "Email protocols"], answer: 0, why: "TLS encrypts the channel — padlock icon." },
        { q: "Encryption AT REST protects…", options: ["Data stored on disks, SSDs and databases", "Live phone calls only", "Battery cells", "Screen pixels"], answer: 0, why: "Covers stored data." },
        { q: "Encryption IN TRANSIT protects…", options: ["Data moving across networks (e.g. between browser and server)", "Furniture", "Cars", "Plants"], answer: 0, why: "Covers data on the wire." },
        { q: "AES is an example of…", options: ["A symmetric encryption algorithm", "A Wi-Fi router model", "A hard disk format", "An antivirus product"], answer: 0, why: "Symmetric block cipher." },
        { q: "RSA is an example of…", options: ["An asymmetric (public-key) encryption algorithm", "A hashing algorithm only", "A database engine", "An operating system"], answer: 0, why: "Public/private key pair cipher." },
        { q: "What happens if an encryption key is leaked to an attacker?", options: ["The confidentiality protection of any data encrypted with that key is broken", "Nothing changes", "The system runs faster", "Code becomes cleaner"], answer: 0, why: "Encryption is only as strong as key secrecy." },
        { q: "In asymmetric encryption, the PUBLIC key is used to…", options: ["Encrypt data — only the matching private key can decrypt it", "Decrypt data that everyone can read", "Sign physical hardware", "Print address labels"], answer: 0, why: "Public encrypts, private decrypts." },
      ],
    },
    {
      id: "firewall-av",
      code: "03",
      title: "Firewalls & Antivirus",
      explanation:
        "Firewalls control network traffic in and out of a system; antivirus / anti-malware detects and removes malicious software. Together they form the perimeter and the immune system.",
      bullets: [
        "Firewall = filters traffic against a rule set (allow/deny).",
        "Packet-filtering firewall: inspects source/destination/port.",
        "Stateful firewall: tracks active connections.",
        "Application firewall: understands specific protocols (e.g. HTTP).",
        "Blocks unauthorised inbound connections + suspicious outbound.",
        "Antivirus uses signature detection: matches known malware patterns.",
        "Heuristic analysis: detects new/unknown malware by suspicious behaviour.",
        "Sandboxing: runs suspicious code in an isolated environment to observe it.",
        "Regular updates are essential — new malware appears daily.",
      ],
      paragraphs: [
        "Signature detection is fast but blind to brand-new malware. Heuristic analysis fills the gap by looking at what a program does — does it try to overwrite system files, contact suspicious servers, encrypt user data? Sandboxing runs the suspect inside a safe virtual environment to watch its behaviour without risk.",
        "Firewalls block unauthorised inbound connections (e.g. attackers scanning your IP) and can also block outbound connections (e.g. malware trying to phone home). Modern systems combine network firewalls (at the router) with host-based firewalls (on each device).",
      ],
      quiz: [
        { q: "A firewall's primary job is to…", options: ["Filter network traffic in and out of a system using a set of allow/deny rules", "Block sunlight", "Block sound", "Water plants"], answer: 0, why: "Network traffic gatekeeper." },
        { q: "Antivirus 'signature' detection identifies malware by…", options: ["Matching files against a database of known malware patterns", "Predicting random text", "Checking Wi-Fi", "Reading battery levels"], answer: 0, why: "Fast but blind to brand-new malware." },
        { q: "Heuristic analysis in antivirus catches…", options: ["New / unknown malware by analysing suspicious BEHAVIOUR", "Only very old malware", "Only files larger than 1 GB", "Hardware faults"], answer: 0, why: "Behaviour-based detection." },
        { q: "Sandboxing runs suspicious code…", options: ["In an isolated environment so its behaviour can be observed without risking the real system", "Directly on the kernel", "Straight onto the main disk", "On the cloud admin account"], answer: 0, why: "Safe observation chamber." },
        { q: "A stateful firewall is different from a simple packet filter because it…", options: ["Tracks the state of active network connections, not just individual packets", "Blocks battery use", "Reads RAM colours", "Scans USB drives only"], answer: 0, why: "Connection-aware filtering." },
        { q: "Modern firewalls can block…", options: ["Unauthorised inbound traffic AND suspicious outbound traffic (e.g. malware phoning home)", "Lightning", "Heat", "Sound"], answer: 0, why: "Bidirectional control." },
        { q: "Why must antivirus signature databases be updated regularly?", options: ["New malware variants appear daily and signatures must be kept current", "To improve screen colours", "To speed up Wi-Fi", "To clean code"], answer: 0, why: "Old signatures miss new threats." },
        { q: "A packet-filtering firewall inspects…", options: ["Packet headers — source/destination addresses and port numbers", "Battery temperature", "Camera lens quality", "Screen size"], answer: 0, why: "Header-level inspection." },
        { q: "Antivirus software can typically…", options: ["Detect, quarantine and remove malicious software", "Build hardware", "Mine metals", "Print PDFs"], answer: 0, why: "Core AV functions." },
        { q: "The BEST protection against malware combines…", options: ["Firewall + antivirus + regular updates + user awareness training", "Just antivirus", "Just a firewall", "Stickers on the laptop"], answer: 0, why: "Layered defence in depth." },
      ],
    },
    {
      id: "backups-raid",
      code: "04",
      title: "Backups & RAID",
      explanation:
        "Backups protect data against loss, theft and ransomware. RAID protects against drive failure by spreading data across multiple disks. Both are about availability.",
      bullets: [
        "Full backup — copy everything (slow, big, simple to restore).",
        "Incremental backup — copy what changed since the LAST backup (fast, complex restore).",
        "Differential backup — copy what changed since the last FULL backup.",
        "3-2-1 rule: 3 copies, 2 different media, 1 offsite.",
        "Offsite / cloud backups protect against fire, theft, ransomware.",
        "RAID 0 — stripes data across drives (speed, NO redundancy).",
        "RAID 1 — mirrors data across two drives (full redundancy, half capacity).",
        "RAID 5 — stripes with parity (good balance of speed, capacity, redundancy).",
        "RAID 10 — combines striping + mirroring (high speed + redundancy).",
        "RAID is NOT a backup — it does not protect against deletion, ransomware or theft.",
      ],
      paragraphs: [
        "Backups are about recoverability. A full backup is simple — one file restores everything. Incremental backups are smaller and faster but to restore you need the last full backup PLUS every incremental since. Differential sits in between: faster than full, simpler than incremental.",
        "The 3-2-1 rule (3 copies on 2 different media with 1 offsite) survives almost any single disaster — fire, flood, theft or ransomware. Cloud backups make the 'offsite' part easy.",
        "RAID protects against hardware failure: if a disk dies, the array keeps running. RAID 1 mirrors, RAID 5 uses parity. But if you delete a file by mistake or ransomware encrypts it, RAID happily mirrors the destruction. That's why RAID is not a backup.",
      ],
      quiz: [
        { q: "A FULL backup copies…", options: ["Every selected file every time (simple to restore, slow and large)", "Only files that changed", "Random files", "Nothing"], answer: 0, why: "Complete copy each run." },
        { q: "An INCREMENTAL backup copies…", options: ["Only files changed since the LAST backup of any kind (small + fast, complex restore)", "Everything every time", "Nothing", "Audio files only"], answer: 0, why: "Smallest delta — restore needs full + all increments." },
        { q: "A DIFFERENTIAL backup copies…", options: ["All files changed since the last FULL backup", "Changes since any backup", "Photos only", "Videos only"], answer: 0, why: "Cumulative since the last full backup." },
        { q: "The 3-2-1 backup rule means…", options: ["3 copies of data, on 2 different media, with 1 copy stored offsite", "3 backups every 2 days plus 1 user", "3 RAID disks + 2 SSDs + 1 HDD", "Random copies"], answer: 0, why: "Industry standard resilience rule." },
        { q: "RAID 1 stores data using…", options: ["Mirroring — full copy on two drives (high redundancy, half capacity)", "Striping only", "Parity only", "Nothing"], answer: 0, why: "Drive failure tolerant." },
        { q: "RAID 0 provides…", options: ["Speed via striping but NO redundancy — one drive failure loses all data", "Full redundancy", "Best of both worlds", "Automatic backups"], answer: 0, why: "Performance, zero fault tolerance." },
        { q: "RAID 5 uses…", options: ["Striping with distributed parity — good balance of speed, capacity and redundancy", "Mirroring only", "Triple mirroring", "No parity at all"], answer: 0, why: "Survives a single drive failure." },
        { q: "Is RAID a substitute for backups?", options: ["No — RAID protects against drive failure but NOT against deletion, ransomware or theft", "Yes always", "Only RAID 1 counts as backup", "Only RAID 5 counts as backup"], answer: 0, why: "RAID happily mirrors ransomware encryption." },
        { q: "An offsite backup specifically protects against…", options: ["Fire, theft and ransomware affecting the main site", "Nothing", "Battery wear", "Screen burn-in"], answer: 0, why: "Geographic redundancy = disaster recovery." },
        { q: "Cloud backup is typically used as…", options: ["The 'offsite' copy in the 3-2-1 rule", "Forbidden by all firms", "Always RAID 0", "Mirror only"], answer: 0, why: "Easy way to get geographic redundancy." },
      ],
    },
    {
      id: "aup",
      code: "05",
      title: "AUP & Human Policies",
      explanation:
        "Technology alone cannot stop attacks. An Acceptable Use Policy (AUP) sets the rules for how staff and students may use systems, with training and monitoring to back it up.",
      bullets: [
        "AUP = Acceptable Use Policy — agreed rules for using IT systems.",
        "Defines permitted activities (work, study) and prohibited ones (illegal, offensive content).",
        "Sets password rules: length, complexity, change frequency.",
        "Covers data handling: where data may be stored, USBs, personal devices.",
        "Covers internet use: streaming, downloads, social media at work.",
        "Specifies consequences for breach (warnings, dismissal, prosecution).",
        "Regular staff training keeps policies current and effective.",
        "Monitoring + logging detect breaches and support investigations.",
      ],
      paragraphs: [
        "An AUP makes responsibilities explicit. New staff sign it on joining, agreeing not to share passwords, install unapproved software or visit prohibited sites. Training reinforces the AUP with practical guidance — how to spot phishing, how to report incidents.",
        "Logging and monitoring complete the picture. If a breach happens, logs show who did what and when. Knowing they're being logged also deters most insider misuse — most people won't risk dismissal or prosecution.",
      ],
      quiz: [
        { q: "AUP stands for…", options: ["Acceptable Use Policy", "Anti-Update Patch", "Adware-Use Permit", "Auto USB Pass"], answer: 0, why: "Standard name for IT usage rules." },
        { q: "An AUP exists to…", options: ["Set the agreed rules for how staff and students may use IT systems", "Set Wi-Fi prices", "Choose hardware brands", "Order office coffee"], answer: 0, why: "Defines acceptable behaviour." },
        { q: "An AUP typically covers rules on…", options: ["Passwords, data handling, internet use and acceptable content", "Snack types only", "Weather", "Plant care"], answer: 0, why: "Broad usage rules." },
        { q: "Possible consequences listed in an AUP for serious breach include…", options: ["Formal warnings, dismissal and possible prosecution", "Free phones", "A holiday bonus", "Free Wi-Fi"], answer: 0, why: "Real enforcement." },
        { q: "Why is regular staff training important alongside an AUP?", options: ["It keeps awareness current and helps staff spot phishing and other attacks", "It tunes pianos", "It makes tea", "It plants trees"], answer: 0, why: "People are the weakest link without training." },
        { q: "Monitoring and logging support security by…", options: ["Detecting breaches and deterring insider misuse", "Speeding up Wi-Fi", "Increasing RAM", "Brightening screens"], answer: 0, why: "Visibility + deterrence." },
        { q: "An AUP's password rules typically specify…", options: ["Minimum length, complexity and change frequency", "Font and colour", "RAM size", "Screen size"], answer: 0, why: "Password policy section." },
        { q: "An AUP usually applies to…", options: ["All staff (and often students/contractors)", "Only the IT department", "Only directors", "Only visitors"], answer: 0, why: "Organisation-wide." },
        { q: "The most effective security combines…", options: ["Technology + policy + human training and awareness", "Just an antivirus", "Just a firewall", "Stickers on monitors"], answer: 0, why: "People + process + tech (defence in depth)." },
        { q: "True/False: a well-enforced AUP can deter careless and malicious insider misuse.", options: ["True", "False"], answer: 0, why: "Clear rules + monitoring + consequences deter misuse." },
      ],
    },
  ],
  flashcards: [
    { category: "AUTH", front: "MFA factors", back: "Something you know (password) + have (token/phone) + are (biometric)." },
    { category: "AUTH", front: "Least privilege", back: "Each user gets only the minimum access needed — limits damage if account is compromised." },
    { category: "ENCRYPTION", front: "Symmetric vs asymmetric", back: "Symmetric = one shared key (fast, AES); asymmetric = public+private key pair (RSA)." },
    { category: "ENCRYPTION", front: "At rest vs in transit", back: "At rest = stored data (disk); in transit = data moving across networks (HTTPS/TLS)." },
    { category: "FIREWALL", front: "Firewall job", back: "Filter network traffic against rules — block unauthorised inbound + suspicious outbound." },
    { category: "ANTIVIRUS", front: "Signature vs heuristic", back: "Signature matches known patterns; heuristic detects unknown malware by behaviour." },
    { category: "ANTIVIRUS", front: "Sandboxing", back: "Run suspect code in an isolated environment to observe it without risk to host system." },
    { category: "BACKUPS", front: "Backup types", back: "Full (everything), Incremental (since last backup), Differential (since last full)." },
    { category: "BACKUPS", front: "3-2-1 rule", back: "3 copies of data, 2 different media, 1 stored offsite." },
    { category: "RAID", front: "RAID summary", back: "0 = stripe (speed only), 1 = mirror, 5 = stripe + parity, 10 = stripe + mirror." },
    { category: "RAID", front: "Is RAID a backup?", back: "NO — RAID protects against drive failure, NOT against deletion, ransomware or theft." },
    { category: "AUP", front: "AUP", back: "Acceptable Use Policy — agreed rules for using IT systems, with consequences for breach." },
  ],
};
