import type { TopicContent } from "./types";

export const threats: TopicContent = {
  slug: "threats",
  hero:
    "Digital systems face constant attack: malware, social engineering, brute force, denial of service and weak access control. This module catalogues the main threats every IGCSE student needs to recognise.",
  tags: ["MALWARE", "SOCIAL ENGINEERING", "BRUTE FORCE", "DOS", "INSIDER", "WEAK"],
  sections: [
    {
      id: "malware",
      code: "01",
      title: "Malware",
      explanation:
        "Malware (malicious software) is any program designed to damage, disrupt or gain unauthorised access to systems. It comes in many flavours — each with a different goal.",
      bullets: [
        "Virus — attaches to legitimate files, spreads when the file runs, often damages data.",
        "Worm — self-replicating; spreads across networks without needing a host file.",
        "Trojan — disguised as legitimate software; opens a back door once installed.",
        "Ransomware — encrypts files and demands payment for the decryption key.",
        "Spyware — secretly monitors activity (keystrokes, screens, cameras).",
        "Adware — bombards the user with ads; may track behaviour.",
        "Rootkit — hides deep in the OS, giving attackers persistent admin access.",
        "Keylogger — records every keystroke including passwords.",
      ],
      paragraphs: [
        "Viruses need a user to run an infected file (e.g. an email attachment). Worms are more dangerous because they self-propagate across networks once a single device is infected — the WannaCry worm infected hundreds of thousands of machines in 2017.",
        "Trojans rely on social trickery: the user installs what they think is a useful program and unknowingly opens a back door. Ransomware combines a trojan delivery with strong encryption — paying the ransom is no guarantee the attacker hands over the key.",
        "Spyware, keyloggers and rootkits all aim to stay hidden. Spyware exfiltrates data; keyloggers capture credentials; rootkits give long-term, low-level control of the machine.",
      ],
      quiz: [
        { q: "A worm differs from a virus mainly because it…", options: ["Self-replicates across networks without needing a host file", "Requires a host file to spread", "Is completely harmless", "Is a piece of hardware"], answer: 0, why: "Worms are network self-propagating — e.g. WannaCry." },
        { q: "Ransomware is malware that…", options: ["Encrypts the victim's files and demands payment for the decryption key", "Cleans the PC", "Speeds up Wi-Fi", "Defragments drives"], answer: 0, why: "Definition — high-profile threat." },
        { q: "A Trojan…", options: ["Disguises itself as legitimate software and opens a back door once installed", "Always self-spreads across networks", "Is a piece of hardware", "Cleans up other malware"], answer: 0, why: "Relies on social trickery + hidden back door." },
        { q: "Spyware mainly…", options: ["Secretly monitors user activity and exfiltrates data", "Cleans malware automatically", "Defragments drives", "Speeds up RAM"], answer: 0, why: "Hidden surveillance." },
        { q: "A keylogger records…", options: ["Every keystroke, including passwords and card numbers", "Free music", "Battery percentages", "Local weather"], answer: 0, why: "Major credential-theft tool." },
        { q: "A rootkit gives an attacker…", options: ["Persistent, hidden, low-level administrator access to the system", "Free public Wi-Fi", "A faster CPU", "More RAM"], answer: 0, why: "Deep system control." },
        { q: "Adware primarily…", options: ["Bombards users with adverts and may track their behaviour", "Encrypts files", "Removes other malware", "Performs backups"], answer: 0, why: "Advertising-driven malware." },
        { q: "True/False: paying a ransomware demand guarantees that files will be returned safely.", options: ["True", "False"], answer: 1, why: "Attackers may not decrypt — and may attack again." },
        { q: "A virus typically begins spreading when…", options: ["A user runs or opens the infected host file (e.g. an email attachment)", "The PC is unplugged", "Wi-Fi is switched off", "A phone rings"], answer: 0, why: "Needs user execution of host." },
        { q: "Which of the following is NOT malware?", options: ["An antivirus scanner", "A Trojan", "A worm", "Ransomware"], answer: 0, why: "Antivirus defends against malware." },
      ],
    },
    {
      id: "social-engineering",
      code: "02",
      title: "Social Engineering",
      explanation:
        "Social engineering attacks target people, not technology. They trick users into giving up credentials, clicking malicious links or making payments to attackers.",
      bullets: [
        "Phishing — fake emails impersonating trusted organisations (banks, schools).",
        "Spear phishing — phishing aimed at one specific person, often using personal details.",
        "Vishing — phishing by phone call.",
        "Smishing — phishing by SMS text.",
        "Pretexting — inventing a scenario to extract information (e.g. fake IT helpdesk).",
        "Baiting — leaving a malicious USB stick for someone to plug in.",
        "Shoulder surfing — watching someone enter a password or PIN.",
        "Tailgating — following an authorised person through a secure door.",
      ],
      paragraphs: [
        "Phishing emails imitate banks or services with urgent language ('Your account will be closed!') and a link to a fake site that captures credentials. Spear phishing is far more dangerous because the attacker has researched the target and writes a convincing, personalised message.",
        "Pretexting attacks often impersonate IT support, asking the user to 'verify' a password. Tailgating bypasses physical security: holding the door open for a stranger feels polite but can let an attacker into the building.",
      ],
      quiz: [
        { q: "Phishing attacks primarily target…", options: ["People — tricking them with fake messages into giving up credentials or money", "Network routers", "Hard disks", "CPU cores"], answer: 0, why: "Social engineering targets humans, not hardware." },
        { q: "Vishing is phishing carried out by…", options: ["A phone call", "An SMS text", "An email", "A malicious USB drop"], answer: 0, why: "'V' for voice." },
        { q: "Smishing is phishing carried out by…", options: ["An SMS text message", "A phone call", "An email", "A USB stick"], answer: 0, why: "'SMS' phishing." },
        { q: "A user receives a highly personalised email referencing their boss, project and recent travel, asking for an urgent bank transfer. This is most likely…", options: ["Spear phishing", "Random spam", "Antivirus alert", "A backup notification"], answer: 0, why: "Targeted, researched, personalised attack." },
        { q: "Tailgating is when an attacker…", options: ["Follows an authorised person through a secure door without their own credentials", "Sends a phishing email", "Drops a USB stick", "Calls the victim"], answer: 0, why: "Physical security bypass." },
        { q: "Shoulder surfing is…", options: ["Watching someone enter a password or PIN to steal it", "Surfing the web", "A beach sport", "An audio attack"], answer: 0, why: "Observation-based attack." },
        { q: "Baiting attacks rely on…", options: ["Curiosity — e.g. a malicious USB stick left for someone to plug in", "Honest, signed emails", "Free Wi-Fi", "Hardware updates"], answer: 0, why: "Curiosity trap delivers malware." },
        { q: "Pretexting (sometimes 'quid pro quo') involves…", options: ["Inventing a scenario (e.g. fake IT support) to trick a target into revealing information", "Encrypting files", "Backing up data", "Updating apps"], answer: 0, why: "Manufactured context to extract info." },
        { q: "The BEST defence against phishing combines…", options: ["User awareness training, careful link checking and multi-factor authentication", "Bigger screen fonts", "Faster Wi-Fi", "More RAM"], answer: 0, why: "Layered defence — people + tech." },
        { q: "Social engineering exploits…", options: ["Human trust, fear and helpfulness", "CPU clock speed", "RAM size", "Screen brightness"], answer: 0, why: "Targets people, not machines." },
      ],
    },
    {
      id: "attacks",
      code: "03",
      title: "Brute Force, DoS & Insider Threats",
      explanation:
        "Some attacks try to crack their way in (brute force), some try to knock systems offline (denial of service), and some come from inside the organisation itself.",
      bullets: [
        "Brute force — trying every possible password until one works.",
        "Dictionary attack — trying common words/phrases first.",
        "Credential stuffing — reusing leaked passwords on other sites.",
        "Denial of Service (DoS) — flooding a system to make it unavailable.",
        "Distributed DoS (DDoS) — same idea but from thousands of devices (botnet).",
        "Insider threat — a current/former employee misusing access.",
        "Accidental insider — a user who clicks a phishing link or misconfigures a system.",
        "Weak / default passwords and unpatched software are major risk factors.",
      ],
      paragraphs: [
        "Brute force is slow against strong passwords but devastating against weak ones. Adding length and symbols turns minutes of attack into millions of years. Dictionary attacks short-cut the process by trying 'password123' first.",
        "DoS attacks can take a website offline by overwhelming its servers; DDoS uses a botnet of compromised devices to amplify the attack to millions of requests per second. Even short outages can cost businesses millions.",
        "Not every attacker is outside. Insider threats — disgruntled employees, contractors, or careless staff — already have legitimate access, which makes them very dangerous and hard to detect.",
      ],
      quiz: [
        { q: "A brute-force attack works by…", options: ["Trying every possible password combination until one succeeds", "Guessing only one password and giving up", "Scanning Wi-Fi randomly", "Using no passwords at all"], answer: 0, why: "Exhaustive search — defeated by length + lockouts." },
        { q: "A dictionary attack speeds up brute force by…", options: ["Trying common words, phrases and known leaked passwords first", "Trying only numbers", "Using only emoji", "Playing audio"], answer: 0, why: "Likely guesses tried first." },
        { q: "Credential stuffing is the attack of…", options: ["Reusing usernames + passwords leaked from one site against many other sites", "Stuffing servers physically", "Sending mass spam", "Encrypting files"], answer: 0, why: "Exploits password reuse." },
        { q: "A Denial of Service (DoS) attack aims to…", options: ["Flood a system with traffic so legitimate users cannot access it (availability attack)", "Clean infected systems", "Encrypt files for ransom", "Perform backups"], answer: 0, why: "Targets availability." },
        { q: "A DDoS attack differs from a DoS attack because it…", options: ["Uses a botnet of many compromised devices to amplify the flood", "Uses only one PC", "Relies on USB sticks", "Uses physical disks"], answer: 0, why: "Distributed = much harder to block." },
        { q: "An insider threat is…", options: ["A current or former employee/contractor misusing legitimate access", "An outside hacker", "A software bug", "Bad weather"], answer: 0, why: "Internal source = harder to detect." },
        { q: "Which is an example of an ACCIDENTAL insider threat?", options: ["A staff member clicking a phishing link and infecting the network", "A scheduled software update", "An external DDoS attack", "A lightning strike"], answer: 0, why: "Careless rather than malicious." },
        { q: "Strong, long, unique passwords mainly defeat…", options: ["Brute-force and dictionary attacks", "Heat damage", "Cold damage", "Rain damage"], answer: 0, why: "Length + complexity + uniqueness." },
        { q: "DoS and DDoS attacks compromise which security property?", options: ["Availability", "Battery life", "Screen colour", "RAM brand"], answer: 0, why: "Confidentiality / Integrity / Availability — A is hit." },
        { q: "Why does unpatched software pose a major risk?", options: ["Known vulnerabilities (sometimes zero-day exploits) remain exploitable until patched", "It makes the device faster", "It increases RAM", "It cleans up code"], answer: 0, why: "Attackers actively scan for unpatched systems." },
      ],
    },
  ],
  flashcards: [
    { category: "MALWARE", front: "Virus vs worm", back: "Virus needs a host file + user action; worm self-replicates across networks." },
    { category: "MALWARE", front: "Trojan", back: "Malware disguised as legitimate software; opens a back door once run." },
    { category: "MALWARE", front: "Ransomware", back: "Encrypts files and demands payment for the decryption key." },
    { category: "MALWARE", front: "Spyware / keylogger / rootkit", back: "Hidden monitoring / keystroke capture / persistent low-level admin access." },
    { category: "SOCIAL", front: "Phishing variants", back: "Phishing (email), spear phishing (targeted), vishing (voice), smishing (SMS)." },
    { category: "SOCIAL", front: "Physical social engineering", back: "Shoulder surfing, tailgating, baiting (malicious USB)." },
    { category: "SOCIAL", front: "Pretexting", back: "Inventing a fake scenario (e.g. IT support) to extract information." },
    { category: "ATTACKS", front: "Brute force", back: "Try every possible password; defeated by strong passwords + MFA + rate limits." },
    { category: "ATTACKS", front: "DoS vs DDoS", back: "DoS = flood from one source; DDoS = flood from many compromised devices (botnet)." },
    { category: "ATTACKS", front: "Insider threat", back: "Current or former staff with legitimate access — malicious or accidental." },
  ],
};
